#####################################
#                                   #
#  HADDOCK3.0 tools makefile        #
#                                   #
#####################################

CPP=g++
CPFLAGS=-O2

EXEC=contact_fcc

all: 
	make $(EXEC)

contact_fcc: contact_fcc.cpp
	$(CPP) $(CPFLAGS) -o contact_fcc contact_fcc.cpp

clean :
	/bin/rm $(EXEC)

