name: haddock3
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.9
  - biopython==1.79
  - jsonpickle==2.1.0
  - numpy==1.22.2
  - pip
  - pyyaml==6.0
  - scipy=1.8.0
  - tox==3.24.5
  - pip:
      - pdb-tools==2.5.0
      - git+https://github.com/joaorodrigues/fcc@fcc2
