run_dir = "autoppar-ens"
molecules = ["neuraminidase-2BAT.pdb", "oseltamivir_ensemble11.pdb"]
[topoaa]
autohis = true
delenph = false
autotoppar = true
[rigidbody]
tolerance = 20
ambig_fname = "ambig-active-rigidbody.tbl"
w_vdw = 1.0
sampling = 20
