run_dir = "prot-grid"
mode = "grid"
ncores = 8
debug = true
molecules = ["data/e2aP_1F3G.pdb", "data/hpr_ensemble.pdb"]
topoaa.autohis = false
topoaa.mol1.nhisd = 0
topoaa.mol1.nhise = 1
topoaa.mol1.hise_1 = 75
topoaa.mol2.nhisd = 1
topoaa.mol2.hisd_1 = 76
topoaa.mol2.nhise = 1
topoaa.mol2.hise_1 = 15
rigidbody.tolerance = 20
rigidbody.ambig_fname = "data/e2a-hpr_air.tbl"
rigidbody.sampling = 20
caprieval.1.reference_fname = "data/e2a-hpr_1GGR.pdb"
seletop.select = 5
flexref.tolerance = 20
flexref.ambig_fname = "data/e2a-hpr_air.tbl"
caprieval.2.reference_fname = "data/e2a-hpr_1GGR.pdb"
emref.tolerance = 20
emref.ambig_fname = "data/e2a-hpr_air.tbl"
clustfcc.min_population = 1
seletopclusts.top_models = 4
caprieval.3.reference_fname = "data/e2a-hpr_1GGR.pdb"
