run_dir = "prot-grid"
mode = "grid"
molecules = [
  "../examples/docking-protein-protein/data/e2aP_1F3G.pdb",
  "../examples/docking-protein-protein/data/hpr_ensemble.pdb",
]
[topoaa]
autohis = false
[topoaa.mol1]
nhisd = 0
nhise = 1
hise_1 = 75
[topoaa.mol2]
nhisd = 1
hisd_1 = 76
nhise = 1
hise_1 = 15
[rigidbody]
tolerance = 5
ambig_fname = "../examples/docking-protein-protein/data/e2a-hpr_air.tbl"
sampling = 1000
["caprieval.1"]
reference_fname = "../examples/docking-protein-protein/data/e2a-hpr_1GGR.pdb"
[seletop]
select = 200
["caprieval.2"]
reference_fname = "../examples/docking-protein-protein/data/e2a-hpr_1GGR.pdb"
[flexref]
tolerance = 5
ambig_fname = "../examples/docking-protein-protein/data/e2a-hpr_air.tbl"
["caprieval.3"]
reference_fname = "../examples/docking-protein-protein/data/e2a-hpr_1GGR.pdb"
[emref]
tolerance = 5
ambig_fname = "../examples/docking-protein-protein/data/e2a-hpr_air.tbl"
["caprieval.4"]
reference_fname = "../examples/docking-protein-protein/data/e2a-hpr_1GGR.pdb"
[clustfcc]
[seletopclusts]
top_models = 4
["caprieval.5"]
reference_fname = "../examples/docking-protein-protein/data/e2a-hpr_1GGR.pdb"
