[params]
noecv = false
npart = 1
dihed = false
noe = true
cdih = false
sani = false
vean = false
xrdc = false
dani = false
xpcs = false
harm = false
zres = false
rg = false
em = false
sym = false
ncs = false
log_level = 'verbose'
dielec = 'cdie'
epsilon1 = 1
waterdock = false
keepwater = false