#=================================================================================================#
# HADDOCK with clustering after rigid-body
#  Cluster the models after rigid-body sampling and refine the top X/N clusters/models
#
# topology > rigid-body > cluster-fcc > select-top-clusters > flexible-refinement > md-refinement
#
#================================================================================================#

order = ["topoaa",
         "rigidbody",
         "clustfcc",
         "seletopclusts",
         "flexref",
         "mdref"]

# this contains only the parameters, no input
[topoaa]
autohis = true

[rigidbody]
ambig = 'ambig.tbl'
sampling = 20

[clustfcc]
contact_distance_cutoff = 5.0
fraction_cutoff = 0.6
threshold = 4

[seletopclusts]
top_cluster = [1, 2, 3, 4] # will select the best one
top_models = 4 # will select the top4 models inside the cluster

[flexref]
ambig = 'ambig.tbl'
cool1_steps = 500

[mdref]
ambig = 'ambig.tbl'
cool1_steps = 10
#========================================================================================#