# ====================================================================
# Protein-protein docking example with NMR-derived ambiguous interaction restraints

# directory in which the scoring will be done
run_dir = "run-grid"

# execution mode
mode = "grid"
ncores = 8

# molecules to be docked
molecules = ["data/e2aP_1F3G.pdb", "data/hpr_ensemble.pdb"]

# ====================================================================
# Parameters for each stage are defined below, prefer full paths
# ====================================================================
[topoaa]
autohis = false
[topoaa.mol1]
nhisd = 0
nhise = 1
hise_1 = 75
[topoaa.mol2]
nhisd = 1
hisd_1 = 76
nhise = 1
hise_1 = 15

[rigidbody]
ambig_fname = "data/e2a-hpr_air.tbl"
sampling = 1000

["caprieval.0"]
reference_fname = "data/e2a-hpr_1GGR.pdb"

[seletop]
select = 200

["caprieval.1"]
reference_fname = "data/e2a-hpr_1GGR.pdb"

[flexref]
ambig_fname = "data/e2a-hpr_air.tbl"

["caprieval.2"]
reference_fname = "data/e2a-hpr_1GGR.pdb"

[emref]
ambig_fname = "data/e2a-hpr_air.tbl"

["caprieval.3"]
reference_fname = "data/e2a-hpr_1GGR.pdb"

[clustfcc]

[seletopclusts]
top_models = 4

["caprieval.4"]
reference_fname = "data/e2a-hpr_1GGR.pdb"

# ====================================================================
