"""Describe the Haddock3 ontology used for communicating between modules."""

import datetime
import itertools
import pickle
from enum import Enum, auto
from os import linesep
from pathlib import Path
from typing import Any, Dict, Generic, Hashable, List, Optional, Tuple, TypeVar

import jsonpickle

from haddock.core.defaults import MODULE_IO_FILE
from haddock.core.typing import FilePath, Union

NaN = float("nan")


class Format(Enum):
    """Input and Output possible formats."""

    PDB = "pdb"
    PDB_ENSEMBLE = "pdb"
    CNS_INPUT = "inp"
    CNS_OUTPUT = "out"
    TOPOLOGY = "psf"
    MATRIX = "matrix"

    def __str__(self) -> str:
        return str(self.value)


class Persistent:
    """Any persistent file generated by this framework."""

    def __init__(
        self,
        file_name: FilePath,
        file_type: Format,
        path: FilePath = ".",
        md5: Optional[str] = None,
        restr_fname: Optional[FilePath] = None,
    ) -> None:
        self.created = datetime.datetime.now().isoformat(" ", "seconds")
        self.file_name = Path(file_name).name
        self.file_type = file_type
        self.path = str(Path(path).resolve())
        self.full_name = str(Path(path, self.file_name))
        self.rel_path = Path("..", Path(self.path).name, file_name)
        self.md5 = md5
        self.restr_fname = restr_fname

    def __repr__(self) -> str:
        rep = f"[{self.file_type}|{self.created}] {Path(self.path) / self.file_name}"
        return rep

    def is_present(self) -> bool:
        """Check if the persisent file exists on disk."""
        return self.rel_path.resolve().exists()


class PDBFile(Persistent):
    """Represent a PDB file."""

    def __init__(
        self,
        file_name: Union[Path, str],
        topology: Optional[Any] = None,
        path: Union[Path, str] = ".",
        score: float = NaN,
        md5: Optional[str] = None,
        restr_fname: Optional[Union[Path, str]] = None,
        unw_energies: Optional[dict[str, float]] = None,
        ligand_top_fname: Optional[Union[Path, str]] = None,
        ligand_param_fname: Optional[Union[Path, str]] = None,
    ) -> None:
        super().__init__(file_name, Format.PDB, path, md5, restr_fname)

        self.topology = topology
        self.score = score
        self.ori_name: Optional[str] = None
        self.clt_id: Union[str, int, None] = None
        self.clt_rank: Optional[int] = None
        self.clt_model_rank: Optional[int] = None
        self.len = score
        self.unw_energies = unw_energies
        self.seed = None
        self.ligand_top_fname = ligand_top_fname
        self.ligand_param_fname = ligand_param_fname

    def __lt__(self, other: "PDBFile") -> bool:
        return self.score < other.score

    def __gt__(self, other: "PDBFile") -> bool:
        return self.score > other.score

    def __eq__(self, other: "PDBFile") -> bool:  # type: ignore
        return self.score == other.score

    def __hash__(self) -> int:
        return id(self)


class RMSDFile(Persistent):
    """Represents a RMSD matrix file."""

    def __init__(self, file_name: FilePath, npairs: int, path: FilePath = ".") -> None:
        super().__init__(file_name, Format.MATRIX, path)
        self.npairs = npairs

    def __hash__(self) -> int:
        return id(self)


class TopologyFile(Persistent):
    """Represent a CNS-generated topology file."""

    def __init__(self, file_name: FilePath, path: FilePath = ".") -> None:
        super().__init__(file_name, Format.TOPOLOGY, path)


class CacheKey(Enum):
    RMSD = auto()


K = TypeVar("K", bound=Hashable)
V = TypeVar("V")


class Cache(Generic[K, V]):
    """Cache with searchable entries by composite keys."""

    def __init__(self):
        # Main storage: key -> list of (search_key, value) tuples
        self._store: Dict[CacheKey, List[Tuple[K, V]]] = {}

        # Initialize with all CacheKey enum values
        for key in CacheKey:
            self._store[key] = []

        # Index for fast lookup: (cache_key, search_key) -> value
        self._index: Dict[Tuple[CacheKey, K], V] = {}

    def add(self, cache_key: CacheKey, search_key: K, value: V) -> None:
        """Add entry with searchable key.

        # Example:
        #  cache.add(CacheKey.RMSD, ("xxx", "yyy", 42.0))

        """
        self._store[cache_key].append((search_key, value))
        self._index[(cache_key, search_key)] = value

    def get(self, cache_key: CacheKey, search_key: K) -> Optional[V]:
        """Retrieve value by search key.

        # Example:
        #  rmsd = cache.get(CacheKey.RMSD, ("xxx", "yyy"))
        """
        return self._index.get((cache_key, search_key))

    def has(self, cache_key: CacheKey, search_key: K) -> bool:
        """Check if entry exists.

        # Example:
        #  cache.has(CacheKey.RMSD, ("xxx", "yyy"))
        """
        return (cache_key, search_key) in self._index

    def get_all(self, cache_key: CacheKey) -> List[Tuple[K, V]]:
        """Get all entries for a cache key."""
        return self._store.get(cache_key, []).copy()

    def clear(self, cache_key: CacheKey) -> None:
        """Clear all entries for a cache key."""
        for search_key, _ in self._store[cache_key]:
            self._index.pop((cache_key, search_key), None)
        # Clear storage
        self._store[cache_key].clear()


class ModuleIO:
    """Intercommunicating modules and exchange input/output information."""

    def __init__(self) -> None:
        self.input: List[Any] = []
        self.output: List[Any] = []
        self.cache: Cache = Cache()

    def add(self, persistent, mode="i"):
        """Add a given filename as input or output."""
        if mode == "i":
            if isinstance(persistent, list):
                self.input.extend(persistent)
            else:
                self.input.append(persistent)
        else:
            if isinstance(persistent, list):
                self.output.extend(persistent)
            else:
                self.output.append(persistent)

    def update_cache(self, cache):
        """Update the internal cache of ModuleIO."""
        self.cache = cache

    def save(self, path: FilePath = ".", filename: FilePath = MODULE_IO_FILE) -> Path:
        """Save Input/Output needed files by this module to disk."""
        fpath = Path(path, filename)
        with open(fpath, "wb") as output_handler:
            data = {"input": self.input, "output": self.output, "cache": self.cache}
            pickle.dump(data, output_handler)
        return fpath

    def load(self, filename: FilePath) -> None:
        """Load the content of a given IO filename."""
        try:
            content = self._load_pkl(filename)
        except Exception as _:
            # ====================================================== #
            # FIXME: In some tests the moduleio file is being used
            #  as input for the test. This try/except only exists
            #  to handle this scenarios - ideally all tests that
            #  use this constructions MUST be redone to account
            #  for the pickle instead of the json
            content = self._load_json(filename)
            # ====================================================== #

        self.input = content["input"]
        self.output = content["output"]
        self.cache = content.get("cache", Cache())

    @staticmethod
    def _load_pkl(filename: FilePath):
        """Load the pickle."""
        with open(file=filename, mode="rb") as fh:
            content = pickle.load(fh)
        return content

    @staticmethod
    def _load_json(filename: FilePath):
        """Try to load a `.json`."""
        _json_filename = Path(filename).with_suffix(".json")
        if _json_filename.exists():
            filename = _json_filename
        with open(file=filename, mode="r") as fh:
            content = jsonpickle.decode(fh.read())
        return content

    def retrieve_models(
        self, crossdock: bool = False, individualize: bool = False
    ) -> list[Union[PDBFile, list[PDBFile]]]:
        """Retrieve the PDBobjects to be used in the module."""
        # Get the models generated in previous step
        model_list: list[PDBFile] = []
        input_dic: dict[int, list[PDBFile]] = {}

        for i, element in enumerate(self.output):
            if isinstance(element, dict):
                position_list: list[PDBFile] = input_dic.setdefault(i, [])
                for key in element:
                    position_list.append(element[key])  # type: ignore

            elif element.file_type == Format.PDB:  # type: ignore
                model_list.append(element)  # type: ignore

        if input_dic and not crossdock and not individualize:
            # check if all ensembles contain the same number of models
            sub_lists = iter(input_dic.values())
            _len = len(next(sub_lists))
            if not all(len(sub) == _len for sub in sub_lists):
                _msg = (
                    "Different number of models in molecules,"
                    " cannot prepare pairwise complexes."
                )
                raise Exception(_msg)

            # prepare pairwise combinations
            model_list = [values for values in zip(*input_dic.values())]  # type: ignore
        elif input_dic and crossdock and not individualize:
            model_list = [values for values in itertools.product(*input_dic.values())]  # type: ignore
        elif input_dic and individualize:
            model_list = list(itertools.chain(*input_dic.values()))

        return model_list  # type: ignore

    def check_faulty(self) -> float:
        """Check how many of the output exists."""
        total = 0.0
        present = 0.0
        for element in self.output:
            if isinstance(element, dict):
                total += len(element)
                present += sum(j.is_present() for j in element.values())
            else:
                total += 1
                if element.is_present():
                    present += 1

        if total == 0:
            _msg = "No expected output was passed to ModuleIO"
            raise Exception(_msg)

        faulty_per = (1 - (present / total)) * 100

        # added this method here to avoid modifying all calls in the
        # modules' run method. We can think about restructure this part
        # in the future.
        self.remove_missing()

        return faulty_per

    def remove_missing(self) -> None:
        """Remove missing structure from `output`."""
        # can't modify a list/dictionary within a loop
        idxs: list[int] = []
        for idx, element in enumerate(self.output):
            if isinstance(element, dict):
                to_pop = []
                for key2 in element:
                    if not element[key2].is_present():
                        to_pop.append(key2)
                for pop_me in to_pop:
                    element.pop(pop_me)
            else:
                if not element.is_present():
                    idxs.append(idx)

        self.output = [value for i, value in enumerate(self.output) if i not in idxs]

    def __repr__(self) -> str:
        return f"Input: {self.input}{linesep}Output: {self.output}"


PDBPath = Union[PDBFile, Path]

PDBPathT = TypeVar("PDBPathT", bound=Union[PDBFile, Path])
"""
Generic type variable for PDBFile or Path.

If the first annotated variable is PDBFile,
the second annotated variable will be PDBFile instead of Path,vice versa.
"""
