"""Canonical dependency and staging helpers for CNS jobs."""

from __future__ import annotations

import fcntl
import os
import re
import shutil
import tempfile
from dataclasses import dataclass, replace
from pathlib import Path

from seamless.checksum.calculate_checksum import (
    calculate_checksum,
    calculate_dict_checksum,
    calculate_file_checksum,
)
from seamless_transformer.cmd.bash_transformation import prepare_bash_transformation
from seamless_transformer.compression_utils import (
    decompress_bytes,
    strip_compression_suffix,
)

from haddock import log
from haddock.core.typing import Optional, Sequence, Union


# The generated Seamless glue is intentionally frozen. The scripts and their
# normalizer are explicit data pins; these checksums cover only the small
# wrapper generated by seamless-run 0.6.1 for each output protocol.
_SEAMLESS_CODE_PINS = {
    "pdb": "f4400f9541e1506cdf2e077f37b6c241f6c82f936dcc9f94b7025e9d9b2f576a",
    "pdb+psf": "1427f07ff1afcb850199a9e96d85df94eb87f80b9c03099f27957b9d7d287725",
}

_NORMALIZER_NAME = "normalize-cns-output.py"
_NORMALIZER_SOURCE = Path(__file__).with_name("libcnsnormalize.py")


_ASSIGNMENT_PATTERNS = (
    # The value is captured greedily, so it runs to the *last* `)` on the
    # line.  A CNS assignment may contain a call -- `$ambig_fname + "_" +
    # encode($count)`, which is how a per-model restraint table is chosen --
    # and a lazy capture stops at the `)` that closes `encode(`, leaving a
    # value no later pattern can recognise.  The file it names is then never
    # recorded as a read, so two models refined against different tables would
    # be indistinguishable.
    re.compile(
        r"eval(?:uate)?\s*\(\s*\$(?P<name>[A-Za-z0-9_]+)\s*=\s*(?P<value>.*)\s*\)"
    ),
    re.compile(r"\{===>\}\s*(?P<name>[A-Za-z0-9_]+)\s*=\s*(?P<value>.*?)\s*;"),
)

_REFERENCE_PATTERN = re.compile(
    r"@@?(?P<target>"
    r"MODULE:[^\s;]+|TOPPAR:[^\s;]+|"
    r"MODULE/[^\s;]+|TOPPAR/[^\s;]+|"
    # An indexed splice such as `@@$input_aa_psf_filename_$nchain` must be
    # matched whole. Without this alternative the next one matches only
    # `$input_aa_psf_filename_`, the index is lost, and the file it names is
    # never recorded as a dependency -- so its path survives canonicalization
    # and the leak check refuses the job.
    r"[$&][A-Za-z0-9_]*_[$&][A-Za-z0-9_]+|"
    r"[$&][A-Za-z0-9_]+|[^\s;]+)"
)
_INDEXED_VARIABLE_REFERENCE_PATTERN = re.compile(
    r"(?P<prefix>[$&][A-Za-z0-9_]*_)(?P<index>[$&][A-Za-z0-9_]+)$"
)
_COUNT_SUFFIX_REFERENCE_PATTERN = re.compile(
    r"(?P<base>[$&][A-Za-z0-9_]+|[^+\s]+)"
    r'\s*\+\s*"(?P<separator>[^"]*)"\s*\+\s*'
    r"encode\(\s*(?P<count>[$&][A-Za-z0-9_]+|\d+)\s*\)"
)
_LOCATOR_COUNT_ASSIGNMENT_PATTERN = re.compile(
    r"(?im)(?P<prefix>"
    r"(?:eval(?:uate)?\s*\(\s*\$|\{===>\}\s*)"
    r"count\s*=\s*"
    r")(?P<value>[^);\r\n]*)(?P<suffix>[);])"
)
_DYNAMIC_TOPPAR_PREFIX_PATTERN = re.compile(
    r'"?(?P<prefix>TOPPAR:[^"\s]+?)"?\s*\+\s*encode\('
)

# These generated CNS variables affect execution identity, but cannot affect
# which files a job reads.  Ignoring only their values lets a scheduler reuse
# dependency analysis across otherwise identical sampling jobs while the full
# script remains part of each job's checksum.
_DEPENDENCY_INDEPENDENT_ASSIGNMENT_PATTERN = re.compile(
    r"(?im)(?P<prefix>"
    r"(?:eval(?:uate)?\s*\(\s*\$|\{===>\}\s*)"
    r"(?P<name>count|output_pdb_filename|seed)\s*=\s*"
    r")(?P<value>[^);\r\n]*)(?P<suffix>[);])"
)
_MAPPING_TEMPLATE_ASSIGNMENTS = frozenset({"seed"})


@dataclass(frozen=True)
class CanonicalDependency:
    """One immutable CNS input in its location-independent role."""

    original_path: Path
    canonical_name: str
    checksum: str


@dataclass(frozen=True)
class CanonicalMapping:
    """The complete, immutable identity mapping of a CNS job.

    The mapping is deliberately independent of run roots and generated file
    names.  It is shared by dependency reporting, reference staging and cache
    checksum construction in later phases.
    """

    canonical_script: str
    dependencies: tuple[CanonicalDependency, ...]
    cns_exec: Path
    output_paths: tuple[Path, ...]
    canonical_output_names: tuple[str, ...]
    output_shape: str
    invariant_dependencies: tuple[str, ...]
    work_dir: Path
    module_dir: Path
    toppar_dir: Path
    unresolved_reads: tuple[str, ...]

    @property
    def checksums(self) -> dict[str, str]:
        """Return the canonical checksum tree used by transformations."""
        return {
            "canonical.inp": calculate_checksum(self.canonical_script.encode()),
            "run-cns.sh": calculate_checksum(canonical_wrapper(self).encode()),
            _NORMALIZER_NAME: _normalizer_checksum(),
            **{dep.canonical_name: dep.checksum for dep in self.dependencies},
        }

    @property
    def dependency_paths(self) -> dict[Path, str]:
        """Map resolved original paths to their canonical names."""
        return {
            dependency.original_path: dependency.canonical_name
            for dependency in self.dependencies
        }


@dataclass(frozen=True)
class CanonicalMappingTemplate:
    """Canonical mapping shared by jobs that differ only in job metadata."""

    mapping: CanonicalMapping
    canonical_script_template: str
    assignment_slots: tuple[tuple[str, str, int], ...]


@dataclass(frozen=True)
class SynthesizedSeamlessRun:
    """A fully materialized reference workspace and its runnable command."""

    stage_dir: Path
    wrapper: Path
    manifest: Path
    command: tuple[str, ...]


def compression_transparent_checksum(path: Path) -> str:
    """Checksum a file as Seamless does, transparently to .gz/.zst storage."""
    path = path.resolve()
    _logical_name, suffix = strip_compression_suffix(path.name)
    if suffix is None:
        checksum = calculate_file_checksum(str(path))
        if checksum is None:
            raise OSError(f"Could not checksum {path}")
        return checksum
    return calculate_checksum(decompress_bytes(path.read_bytes(), suffix))


def build_canonical_mapping(
    input_file: Path | str,
    *,
    envvars: dict[str, str],
    cns_exec: Path,
    output_files: Sequence[Path] = (),
    output_pdb_files: Sequence[Path] = (),
    work_dir: Path | None = None,
    invariant_checksums: dict[Path, str] | None = None,
    dependency_scan: CNSDependencyScan | None = None,
) -> CanonicalMapping:
    """Resolve every CNS read and rewrite the job into canonical names.

    ``input_file`` may be a materialized script or the in-memory input passed
    to CNS.  ``work_dir`` is captured by :class:`CNSJob` before multiprocessing
    so relative names do not depend on a worker's current directory.
    """
    work_dir = (work_dir or Path.cwd()).resolve()
    module_dir = _resolve_env_path(envvars["MODULE"], work_dir)
    toppar_dir = _resolve_env_path(envvars["TOPPAR"], work_dir)
    script = _cns_job_script(input_file, work_dir)
    scan = dependency_scan or _scan_cns_job_dependencies(input_file, envvars, work_dir)
    if scan.unresolved_reads:
        # A read this scan could not resolve is a file the job opens whose
        # content is therefore absent from its identity.  Two jobs differing
        # only in that file would be indistinguishable, and the cache would
        # serve one for the other.  Recording it and continuing is not an
        # option: the record has no reader, and a job that cannot be described
        # completely must not be described at all.
        unresolved = ", ".join(scan.unresolved_reads)
        raise ValueError(f"Canonical CNS input has unresolved reads: {unresolved}")
    read_files = scan.read_files

    paths = list(dict.fromkeys(path.resolve() for path in read_files))
    variables = _script_path_variables(script, work_dir, module_dir, toppar_dir)
    canonical_names = _canonical_dependency_names(
        paths, module_dir, toppar_dir, variables
    )
    dependencies = tuple(
        CanonicalDependency(
            path,
            canonical_names[path],
            invariant_checksums.get(path)
            if invariant_checksums is not None and path in invariant_checksums
            else compression_transparent_checksum(path),
        )
        for path in paths
    )
    normalized_outputs = tuple(_absolute_path(path, work_dir) for path in output_files)
    pdb_outputs = {_absolute_path(path, work_dir) for path in output_pdb_files}
    for output in normalized_outputs:
        if output.suffix == ".pdb":
            pdb_outputs.add(output)
    if len(pdb_outputs) != 1 or len(normalized_outputs) not in (1, 2):
        raise ValueError(
            "A cacheable CNS job must declare exactly one PDB and at most one PSF output."
        )
    pdb_output = next(iter(pdb_outputs))
    psf_outputs = [output for output in normalized_outputs if output.suffix == ".psf"]
    if len(psf_outputs) > 1:
        raise ValueError("A cacheable CNS job may declare at most one PSF output.")
    canonical_output_names = ("canonical-output.pdb",) + (
        ("canonical-output.psf",) if psf_outputs else ()
    )
    output_name_map = {pdb_output: "canonical-output.pdb"}
    if psf_outputs:
        output_name_map[psf_outputs[0]] = "canonical-output.psf"

    canonical_script = _rewrite_canonical_script(
        script,
        work_dir,
        module_dir,
        toppar_dir,
        {
            dependency.original_path: dependency.canonical_name
            for dependency in dependencies
        },
        output_name_map,
        text_names=_script_dependency_aliases(
            script, work_dir, module_dir, toppar_dir, canonical_names
        ),
    )
    _assert_canonical_script(
        canonical_script,
        work_dir,
        module_dir,
        toppar_dir,
        [
            *[
                dependency.original_path
                for dependency in dependencies
                if not dependency.canonical_name.startswith(("module/", "toppar/"))
            ],
            *normalized_outputs,
        ],
        [
            *[dependency.canonical_name for dependency in dependencies],
            *output_name_map.values(),
        ],
        canonical_output_names,
    )
    cns_exec = _absolute_path(cns_exec, work_dir)
    return CanonicalMapping(
        canonical_script=canonical_script,
        dependencies=dependencies,
        cns_exec=cns_exec,
        output_paths=(pdb_output, *psf_outputs),
        canonical_output_names=canonical_output_names,
        output_shape="pdb+psf" if psf_outputs else "pdb",
        invariant_dependencies=tuple(
            sorted(
                ["canonical-cns", "run-cns.sh", _NORMALIZER_NAME]
                + [
                    dependency.canonical_name
                    for dependency in dependencies
                    if dependency.canonical_name.startswith(("module/", "toppar/"))
                ]
            )
        ),
        work_dir=work_dir,
        module_dir=module_dir,
        toppar_dir=toppar_dir,
        unresolved_reads=tuple(scan.unresolved_reads),
    )


def canonical_mapping_for_job(job) -> CanonicalMapping:
    """Build the canonical mapping for a CNSJob without importing its class."""
    template = getattr(job, "cache_mapping_template", None)
    if template is not None:
        return _specialize_canonical_mapping(template, job)
    return build_canonical_mapping(
        job.input_file,
        envvars=job.envvars,
        cns_exec=Path(job.cns_exec),
        output_files=job.output_files,
        output_pdb_files=job.output_pdb_files,
        work_dir=job.work_dir,
        invariant_checksums=getattr(job, "cache_invariant_checksums", None),
        dependency_scan=getattr(job, "cache_dependency_scan", None),
    )


def _cns_job_script(input_file: Path | str, work_dir: Path) -> str:
    """Read a materialized CNS input or return its in-memory contents."""
    if isinstance(input_file, Path):
        return _absolute_path(input_file, work_dir).read_text(encoding="utf-8")
    return input_file


def _scan_cns_job_dependencies(
    input_file: Path | str, envvars: dict[str, str], work_dir: Path
) -> CNSDependencyScan:
    """Resolve the files read by a materialized or in-memory CNS input."""
    if isinstance(input_file, Path):
        script_path = _absolute_path(input_file, work_dir)
        scan = scan_cns_dependencies(script_path, envvars)
        return CNSDependencyScan(
            [path for path in scan.read_files if path != script_path],
            scan.unresolved_reads,
        )

    with tempfile.NamedTemporaryFile(
        mode="w", encoding="utf-8", dir=work_dir, suffix=".inp", delete=False
    ) as handle:
        handle.write(input_file)
        temporary_input = Path(handle.name)
    try:
        scan = scan_cns_dependencies(temporary_input, envvars)
        return CNSDependencyScan(
            [path for path in scan.read_files if path != temporary_input.resolve()],
            scan.unresolved_reads,
        )
    finally:
        temporary_input.unlink(missing_ok=True)


def _dependency_scan_key(
    input_file: Path | str, envvars: dict[str, str], work_dir: Path
) -> tuple[Path, Path, Path, str]:
    """Identify jobs whose CNS dependency resolution is equivalent."""
    script = _cns_job_script(input_file, work_dir)
    normalized_script = _DEPENDENCY_INDEPENDENT_ASSIGNMENT_PATTERN.sub(
        r"\g<prefix><job-specific>\g<suffix>", script
    )
    return (
        work_dir,
        _resolve_env_path(envvars["MODULE"], work_dir),
        _resolve_env_path(envvars["TOPPAR"], work_dir),
        normalized_script,
    )


def _canonical_mapping_template(mapping: CanonicalMapping) -> CanonicalMappingTemplate:
    """Replace job-varying canonical assignments with indexed slots."""
    assignment_counts: dict[str, int] = {}
    assignment_slots: list[tuple[str, str, int]] = []

    def replace_assignment(match: re.Match) -> str:
        name = match.group("name").lower()
        if name not in _MAPPING_TEMPLATE_ASSIGNMENTS:
            return match.group(0)
        index = assignment_counts.get(name, 0)
        assignment_counts[name] = index + 1
        slot = f"__HADDOCK_CANONICAL_{name.upper()}_{index}__"
        assignment_slots.append((slot, name, index))
        return f"{match.group('prefix')}{slot}{match.group('suffix')}"

    canonical_script_template = _DEPENDENCY_INDEPENDENT_ASSIGNMENT_PATTERN.sub(
        replace_assignment, mapping.canonical_script
    )
    return CanonicalMappingTemplate(
        mapping,
        canonical_script_template,
        tuple(assignment_slots),
    )


def _specialize_canonical_mapping(
    template: CanonicalMappingTemplate, job
) -> CanonicalMapping:
    """Materialize one job's cheap specialization of a canonical template."""
    script = _cns_job_script(job.input_file, Path(job.work_dir).resolve())
    assignment_values: dict[str, list[str]] = {}
    for match in _DEPENDENCY_INDEPENDENT_ASSIGNMENT_PATTERN.finditer(script):
        name = match.group("name").lower()
        if name in _MAPPING_TEMPLATE_ASSIGNMENTS:
            assignment_values.setdefault(name, []).append(match.group("value"))

    canonical_script = template.canonical_script_template
    for slot, name, index in template.assignment_slots:
        try:
            value = assignment_values[name][index]
        except (KeyError, IndexError) as error:
            raise ValueError(
                f"CNS mapping template expected assignment {name}[{index}]"
            ) from error
        canonical_script = canonical_script.replace(slot, value, 1)

    work_dir = Path(job.work_dir).resolve()
    normalized_outputs = tuple(
        _absolute_path(path, work_dir) for path in job.output_files
    )
    pdb_outputs = {_absolute_path(path, work_dir) for path in job.output_pdb_files}
    for output in normalized_outputs:
        if output.suffix == ".pdb":
            pdb_outputs.add(output)
    if len(pdb_outputs) != 1 or len(normalized_outputs) not in (1, 2):
        raise ValueError(
            "A cacheable CNS job must declare exactly one PDB and at most one PSF output."
        )
    psf_outputs = [output for output in normalized_outputs if output.suffix == ".psf"]
    if len(psf_outputs) > 1:
        raise ValueError("A cacheable CNS job may declare at most one PSF output.")
    return replace(
        template.mapping,
        canonical_script=canonical_script,
        output_paths=(next(iter(pdb_outputs)), *psf_outputs),
    )


def precompute_invariant_checksums_for_jobs(
    jobs,
) -> tuple[dict[Path, set[str]], dict[Path, str]]:
    """Scan equivalent jobs once and checksum selected invariants once.

    CNS inputs and model-specific files remain deliberately absent from the
    returned checksum cache: their checksum belongs to the individual worker
    job.  The reusable dependency scan is attached to each job so worker-side
    canonical mapping does not repeat the recursive CNS analysis.
    """
    manifests: dict[Path, set[str]] = {}
    checksums: dict[Path, str] = {}
    dependency_scans: dict[tuple[Path, Path, Path, str], CNSDependencyScan] = {}
    mapping_groups: dict[tuple, list] = {}
    for job in jobs:
        if not all(
            hasattr(job, attribute)
            for attribute in ("input_file", "envvars", "cns_exec", "work_dir")
        ):
            continue
        work_dir = Path(job.work_dir).resolve()
        module_dir = _resolve_env_path(job.envvars["MODULE"], work_dir)
        toppar_dir = _resolve_env_path(job.envvars["TOPPAR"], work_dir)
        scan_key = _dependency_scan_key(job.input_file, job.envvars, work_dir)
        scan = dependency_scans.get(scan_key)
        if scan is None:
            scan = _scan_cns_job_dependencies(job.input_file, job.envvars, work_dir)
            dependency_scans[scan_key] = scan
        job.cache_dependency_scan = scan
        if all(
            hasattr(job, attribute)
            for attribute in ("output_files", "output_pdb_files")
        ):
            output_signature = (
                tuple(path.suffix for path in job.output_files),
                tuple(path.suffix for path in job.output_pdb_files),
            )
            mapping_key = (
                scan_key,
                _absolute_path(Path(job.cns_exec), work_dir),
                output_signature,
            )
            mapping_groups.setdefault(mapping_key, []).append(job)
        selected: set[Path] = set()
        names: set[str] = set()
        for path in scan.read_files:
            path = path.resolve()
            if path.is_relative_to(module_dir):
                selected.add(path)
                names.add(f"module/{path.relative_to(module_dir).as_posix()}")
            elif path.is_relative_to(toppar_dir):
                selected.add(path)
                names.add(f"toppar/{path.relative_to(toppar_dir).as_posix()}")
        manifests.setdefault(work_dir, set()).update(names)
        for path in selected:
            if path not in checksums:
                checksums[path] = compression_transparent_checksum(path)
    # Dependency scans and installed-file checksums are safely reusable.  A
    # complete mapping is not: topology/refinement jobs can have identical
    # scan shapes while binding distinct content-bearing inputs.  Building the
    # small per-job mapping in the worker preserves content identity.
    log.debug(
        "Analyzed %d dependency patterns and %d mapping templates for %d "
        "cacheable CNS jobs",
        len(dependency_scans),
        len(mapping_groups),
        len(jobs),
    )
    return manifests, checksums


def canonical_wrapper(mapping: CanonicalMapping) -> str:
    """Return the exact ``run-cns.sh`` input used by Seamless."""
    outputs = " ".join(mapping.canonical_output_names)
    code = (
        "#!/bin/sh\n"
        "set -eu\n"
        "stage_dir=$(pwd -P)\n"
        'export TOPPAR="$stage_dir/toppar"\n'
        'export MODULE="$stage_dir/module"\n'
        "export MODDIR=.\n"
        "chmod +x canonical-cns\n"
        "./canonical-cns < canonical.inp > canonical.out\n"
        f"python3 {_NORMALIZER_NAME} {outputs}\n"
    )
    if mapping.output_shape == "pdb":
        code += "cat canonical-output.pdb\n"
    return code


def transformation_for_mapping(mapping: CanonicalMapping) -> tuple[str, dict]:
    """Construct the same transformation emitted by ``seamless-run``."""
    result_targets = (
        None
        if mapping.output_shape == "pdb"
        else {name: name for name in mapping.canonical_output_names}
    )
    checksum, transformation = prepare_bash_transformation(
        "run-cns.sh",
        mapping.checksums,
        directories=[],
        make_executables=["run-cns.sh"],
        result_targets=result_targets,
        capture_stdout=mapping.output_shape == "pdb",
        environment={},
        meta={},
        variables=None,
        meta_variables=None,
        meta_file_checksums={"canonical-cns": _cns_executable_checksum(mapping)},
        dry_run=True,
    )
    actual_code_pin = transformation["code"][2]
    expected_code_pin = _SEAMLESS_CODE_PINS[mapping.output_shape]
    if actual_code_pin != expected_code_pin:
        raise RuntimeError(
            "seamless-run generated code changed: "
            f"expected {expected_code_pin}, got {actual_code_pin}"
        )
    return str(checksum), transformation


def job_checksum(mapping: CanonicalMapping) -> str:
    """Return the trusted transformation checksum that identifies one job."""
    return transformation_for_mapping(mapping)[0]


def result_checksum(mapping: CanonicalMapping) -> str:
    """Checksum final normalized result bytes in Seamless-compatible form."""
    return result_checksum_for_paths(
        mapping.canonical_output_names, mapping.output_paths
    )


def result_checksum_for_paths(names: Sequence[str], paths: Sequence[Path]) -> str:
    """Checksum PDB-only or PDB+PSF result files in canonical output order."""
    if len(paths) == 1:
        return compression_transparent_checksum(paths[0])
    return calculate_dict_checksum(
        {
            name: compression_transparent_checksum(path)
            for name, path in zip(names, paths)
        }
    )


def synthesize_seamless_run(
    mapping: CanonicalMapping,
    stage_dir: Path,
    object_dir: Path | None = None,
) -> SynthesizedSeamlessRun:
    """Stage the exact canonical workspace for an executable reference run."""
    stage_dir = stage_dir.resolve()
    stage_dir.mkdir(parents=True, exist_ok=True)
    object_dir = (object_dir or stage_dir.parent / ".objects").resolve()
    _stage_bytes(
        mapping.canonical_script.encode(),
        stage_dir / "canonical.inp",
        object_dir,
    )
    _stage_file(
        mapping.cns_exec, stage_dir / "canonical-cns", object_dir, executable=True
    )
    for dependency in mapping.dependencies:
        _stage_file(
            dependency.original_path,
            stage_dir / dependency.canonical_name,
            object_dir,
        )
    _stage_file(_NORMALIZER_SOURCE, stage_dir / _NORMALIZER_NAME, object_dir)
    wrapper = stage_dir / "run-cns.sh"
    _stage_bytes(
        canonical_wrapper(mapping).encode(),
        wrapper,
        object_dir,
        executable=True,
    )
    manifest = stage_dir / "inputs.txt"
    _stage_bytes(
        (
            "\n".join(
                [
                    "canonical.inp",
                    _NORMALIZER_NAME,
                    *[dependency.canonical_name for dependency in mapping.dependencies],
                ]
            )
            + "\n"
        ).encode(),
        manifest,
        object_dir,
    )
    command_parts = [
        "seamless-run",
        "-y",
        "-g1",
        "-w",
        str(stage_dir),
        "--local",
        "--input-file",
        str(manifest),
        "--metafile",
        str(stage_dir / "canonical-cns"),
    ]
    if mapping.output_shape == "pdb+psf":
        for output in mapping.canonical_output_names:
            command_parts.extend(("--capture", f"{output}:{stage_dir / output}"))
    command_parts.append(str(wrapper))
    return SynthesizedSeamlessRun(
        stage_dir,
        wrapper,
        manifest,
        tuple(command_parts),
    )


def stage_debug_synthesis(
    mapping: CanonicalMapping,
    job_checksum_: str,
) -> SynthesizedSeamlessRun:
    """Create a process-safe retained reference workspace for one debug job."""
    stage_root = mapping.work_dir / ".cache-stage"
    stage_root.mkdir(exist_ok=True)
    object_dir = stage_root / ".objects"
    target = stage_root / job_checksum_
    lock_path = stage_root / ".lock"
    with open(lock_path, "a+", encoding="utf-8") as lock:
        fcntl.flock(lock.fileno(), fcntl.LOCK_EX)
        try:
            if not target.exists():
                temporary = stage_root / f".{job_checksum_}.{os.getpid()}.tmp"
                shutil.rmtree(temporary, ignore_errors=True)
                synthesize_seamless_run(mapping, temporary, object_dir)
                os.replace(temporary, target)
            return synthesize_seamless_run(mapping, target, object_dir)
        finally:
            fcntl.flock(lock.fileno(), fcntl.LOCK_UN)


def _normalizer_checksum() -> str:
    checksum = calculate_file_checksum(str(_NORMALIZER_SOURCE))
    if checksum is None:
        raise OSError(f"Could not checksum {_NORMALIZER_SOURCE}")
    return checksum


def _cns_executable_checksum(mapping: CanonicalMapping) -> str:
    checksum = calculate_file_checksum(str(mapping.cns_exec))
    if checksum is None:
        raise OSError(f"Could not checksum {mapping.cns_exec}")
    return checksum


def _stage_file(
    source: Path,
    destination: Path,
    object_dir: Path,
    executable: bool = False,
) -> None:
    """Hardlink logical source bytes from the stage's content object pool."""
    source = source.resolve()
    _logical_name, compression = strip_compression_suffix(source.name)
    content = source.read_bytes()
    if compression is not None:
        content = decompress_bytes(content, compression)
    _stage_bytes(content, destination, object_dir, executable=executable)


def _stage_bytes(
    content: bytes,
    destination: Path,
    object_dir: Path,
    executable: bool = False,
) -> None:
    """Store bytes once and hardlink them into a staged job directory."""
    checksum = str(calculate_checksum(content))
    kind = "x" if executable else "r"
    object_path = object_dir / f"{checksum}.{kind}"
    object_dir.mkdir(parents=True, exist_ok=True)
    if not object_path.exists():
        temporary = object_dir / f".{object_path.name}.{os.getpid()}.tmp"
        temporary.write_bytes(content)
        temporary.chmod(0o555 if executable else 0o444)
        try:
            os.link(temporary, object_path)
        except FileExistsError:
            pass
        finally:
            temporary.unlink(missing_ok=True)
    elif object_path.read_bytes() != content:
        raise OSError(f"Stage object checksum collision: {object_path}")

    destination.parent.mkdir(parents=True, exist_ok=True)
    if destination.exists():
        if destination.samefile(object_path):
            return
        destination.unlink()
    os.link(object_path, destination)


def write_cns_dependencies(
    step_dir: Path, invariant_dependencies: CanonicalMapping | Sequence[str]
) -> None:
    """Atomically union a scheduler batch's invariant dependencies into its manifest."""
    if isinstance(invariant_dependencies, CanonicalMapping):
        invariant_dependencies = invariant_dependencies.invariant_dependencies
    step_dir = step_dir.resolve()
    manifest_path = step_dir / "CNS_DEPENDENCIES"
    current = (
        set(manifest_path.read_text(encoding="utf-8").splitlines())
        if manifest_path.exists()
        else set()
    )
    current.update(invariant_dependencies)
    temporary = step_dir / f".CNS_DEPENDENCIES.{os.getpid()}.tmp"
    temporary.write_text("\n".join(sorted(current)) + "\n", encoding="utf-8")
    os.replace(temporary, manifest_path)


@dataclass
class CNSDependencyScan:
    """Resolved CNS read dependencies for one job."""

    read_files: list[Path]
    unresolved_reads: list[str]


@dataclass
class StagedCNSJob:
    """Canonical staged CNS job layout for a reference invocation."""

    stage_dir: Path
    run_root: Path
    module_dir: Path
    toppar_dir: Path
    cns_exec: Path
    staged_job_dir: Path
    staged_input_file: Path
    staged_cns_exec: Path
    staged_module_dir: Path
    staged_toppar_dir: Path

    def staged_path(self, path: Path) -> Path:
        """Return the canonical staged path for an original path."""
        return _canonical_stage_path(
            path,
            stage_dir=self.stage_dir,
            run_root=self.run_root,
            module_dir=self.module_dir,
            toppar_dir=self.toppar_dir,
            cns_exec=self.cns_exec,
        )


class _IgnoredReference:
    """Sentinel for optional references that do not resolve to a file."""


IGNORED_REFERENCE = _IgnoredReference()


def scan_cns_dependencies(
    input_file: Path, envvars: dict[str, str]
) -> CNSDependencyScan:
    """Resolve explicit CNS read dependencies for Seamless execution."""
    input_file = input_file.resolve()
    workdir = input_file.parent
    module_dir = _resolve_env_path(envvars["MODULE"], workdir)
    toppar_dir = _resolve_env_path(envvars["TOPPAR"], workdir)

    # Discovery order, not sorted order.  Canonical pin names are handed out
    # in the order a job first references its inputs, so that the pin a file
    # occupies is a property of the *job* rather than of what the file happens
    # to be called.  Sorting here numbers the pins by filename, so a model
    # that is merely renamed -- which is all a change of rank amounts to --
    # lands on a different pin, changes the canonical script, and changes the
    # job's identity.  That is the one thing this representation exists to
    # prevent.
    read_files: list[Path] = []
    seen_read_files: set[Path] = set()
    unresolved_reads: list[str] = []
    visited: set[Path] = set()

    def add_read_file(path: Path) -> None:
        if path in seen_read_files:
            return
        seen_read_files.add(path)
        read_files.append(path)

    def scan_file(path: Path, variables: dict[str, str]) -> None:
        path = path.resolve()
        if path in visited:
            return
        visited.add(path)

        if not path.exists():
            unresolved_reads.append(str(path))
            return

        add_read_file(path)
        local_vars = dict(variables)

        guard_stack: list[tuple[str, bool]] = []

        for raw_line in path.read_text(encoding="utf-8", errors="ignore").splitlines():
            line = raw_line.split("!", 1)[0].strip()
            if not line:
                continue

            lowered = line.lower()
            if lowered.startswith("if ("):
                guard_var = _extract_nonempty_guard_variable(line)
                if guard_var is not None:
                    guard_stack.append((guard_var, True))
            elif lowered.startswith("end if") and guard_stack:
                guard_stack.pop()

            for pattern in _ASSIGNMENT_PATTERNS:
                match = pattern.search(line)
                if match:
                    value = _normalize_assignment_value(match.group("value"))
                    local_vars[match.group("name")] = value
                    dynamic_prefix = _extract_dynamic_toppar_prefix(value)
                    if dynamic_prefix is not None:
                        local_vars[f"__dynamic_prefix__{match.group('name')}"] = (
                            dynamic_prefix
                        )
                    break

            for match in _REFERENCE_PATTERN.finditer(line):
                token = match.group("target")
                resolved = _resolve_reference(
                    token=token,
                    current_file=path,
                    workdir=workdir,
                    module_dir=module_dir,
                    toppar_dir=toppar_dir,
                    variables=local_vars,
                )
                if resolved is IGNORED_REFERENCE:
                    continue
                if resolved is None:
                    if _is_guarded_optional_reference(token, guard_stack):
                        continue
                    unresolved_reads.append(token)
                    continue
                if isinstance(resolved, list):
                    for resolved_path in resolved:
                        if not resolved_path.exists():
                            unresolved_reads.append(str(resolved_path))
                            continue
                        add_read_file(resolved_path)
                        if resolved_path.suffix.lower() == ".cns":
                            scan_file(resolved_path, local_vars)
                    continue
                if not isinstance(resolved, Path):
                    continue
                if not resolved.exists():
                    unresolved_reads.append(str(resolved))
                    continue

                add_read_file(resolved)
                if resolved.suffix.lower() == ".cns":
                    scan_file(resolved, local_vars)

    scan_file(input_file, {})
    return CNSDependencyScan(
        read_files=list(read_files),
        unresolved_reads=sorted(set(unresolved_reads)),
    )


def stage_cns_job(
    *,
    input_file: Path,
    envvars: dict[str, str],
    cns_exec: Path,
    read_files: Sequence[Path],
) -> StagedCNSJob:
    """Stage a CNS job in a canonical tree with stable workspace paths."""
    input_file = input_file.resolve()
    cns_exec = cns_exec.resolve()
    job_dir = input_file.parent
    run_root = job_dir.parent
    module_dir = _resolve_env_path(envvars["MODULE"], job_dir)
    toppar_dir = _resolve_env_path(envvars["TOPPAR"], job_dir)
    stage_dir = Path(tempfile.mkdtemp(prefix="haddock-seamless-"))

    staged_input_file = _copy_into_stage(
        input_file,
        stage_dir=stage_dir,
        run_root=run_root,
        module_dir=module_dir,
        toppar_dir=toppar_dir,
        cns_exec=cns_exec,
    )
    staged_cns_exec = _copy_into_stage(
        cns_exec,
        stage_dir=stage_dir,
        run_root=run_root,
        module_dir=module_dir,
        toppar_dir=toppar_dir,
        cns_exec=cns_exec,
    )
    for dependency in read_files:
        _copy_into_stage(
            dependency,
            stage_dir=stage_dir,
            run_root=run_root,
            module_dir=module_dir,
            toppar_dir=toppar_dir,
            cns_exec=cns_exec,
        )

    staged_job_dir = stage_dir / "run" / job_dir.relative_to(run_root)
    staged_module_dir = stage_dir / "module"
    staged_toppar_dir = stage_dir / "toppar"
    return StagedCNSJob(
        stage_dir=stage_dir,
        run_root=run_root,
        module_dir=module_dir,
        toppar_dir=toppar_dir,
        cns_exec=cns_exec,
        staged_job_dir=staged_job_dir,
        staged_input_file=staged_input_file,
        staged_cns_exec=staged_cns_exec,
        staged_module_dir=staged_module_dir,
        staged_toppar_dir=staged_toppar_dir,
    )


def make_seamless_wrapper(stage_dir: Path) -> Path:
    """Create the tiny wrapper script used by seamless-run."""
    wrapper = stage_dir / "run-cns.sh"
    wrapper.write_text(
        "#!/bin/sh\n"
        "set -u\n"
        'cd "$JOB_DIR"\n'
        "export MODDIR=.\n"
        'export MODULE="$MODULE_DIR"\n'
        'export TOPPAR="$TOPPAR_DIR"\n'
        'chmod +x "$CNS_EXEC"\n'
        '"$CNS_EXEC" < "$INPUT_FILE" > "$STDOUT_FILE"\n',
        encoding="utf-8",
    )
    wrapper.chmod(0o755)
    return wrapper


def _copy_into_stage(
    source: Path,
    *,
    stage_dir: Path,
    run_root: Path,
    module_dir: Path,
    toppar_dir: Path,
    cns_exec: Path,
) -> Path:
    destination = _canonical_stage_path(
        source,
        stage_dir=stage_dir,
        run_root=run_root,
        module_dir=module_dir,
        toppar_dir=toppar_dir,
        cns_exec=cns_exec,
    )
    source = source.resolve()
    destination.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(source, destination)
    if os.access(source, os.X_OK):
        destination.chmod(destination.stat().st_mode | 0o111)
    return destination


def _canonical_stage_path(
    source: Path,
    *,
    stage_dir: Path,
    run_root: Path,
    module_dir: Path,
    toppar_dir: Path,
    cns_exec: Path,
) -> Path:
    """Map an original path to a stable path inside the staged workspace."""
    source = source.resolve()
    if source == cns_exec.resolve():
        return stage_dir / "bin" / cns_exec.name
    if source.is_relative_to(run_root):
        return stage_dir / "run" / source.relative_to(run_root)
    if source.is_relative_to(module_dir):
        return stage_dir / "module" / source.relative_to(module_dir)
    if source.is_relative_to(toppar_dir):
        return stage_dir / "toppar" / source.relative_to(toppar_dir)
    return stage_dir / "external" / source.as_posix().lstrip(os.sep)


def _script_path_variables(
    script: str,
    work_dir: Path,
    module_dir: Path,
    toppar_dir: Path,
) -> dict[Path, str]:
    """Associate assignment variables with resolved paths for named roles."""
    result: dict[Path, str] = {}
    variables: dict[str, str] = {}
    for line in script.splitlines():
        for pattern in _ASSIGNMENT_PATTERNS:
            match = pattern.search(line)
            if match is None:
                continue
            variable = match.group("name")
            value = _normalize_assignment_value(match.group("value"))
            variables[variable] = value
            resolved = _resolve_count_suffix_reference(
                token=value,
                current_file=work_dir / "canonical.inp",
                workdir=work_dir,
                module_dir=module_dir,
                toppar_dir=toppar_dir,
                variables=variables,
                seen_variables=set(),
            )
            if resolved is None:
                resolved = _resolve_reference(
                    token=value,
                    current_file=work_dir / "canonical.inp",
                    workdir=work_dir,
                    module_dir=module_dir,
                    toppar_dir=toppar_dir,
                    variables=variables,
                )
            if isinstance(resolved, Path) and resolved.exists():
                result[resolved.resolve()] = _canonical_role_variable(
                    variable,
                    value,
                )
            break
    return result


def _script_dependency_aliases(
    script: str,
    work_dir: Path,
    module_dir: Path,
    toppar_dir: Path,
    canonical_names: dict[Path, str],
) -> dict[str, str]:
    """Map textual dependency aliases to the resolved canonical role name."""
    aliases: dict[str, str] = {}
    variables: dict[str, str] = {}
    for line in script.splitlines():
        for pattern in _ASSIGNMENT_PATTERNS:
            match = pattern.search(line)
            if match is None:
                continue
            variable = match.group("name")
            value = _normalize_assignment_value(match.group("value"))
            variables[variable] = value
            dynamic_prefix = _extract_dynamic_toppar_prefix(value)
            if dynamic_prefix is not None:
                variables[f"__dynamic_prefix__{variable}"] = dynamic_prefix

            resolved = _resolve_count_suffix_reference(
                token=value,
                current_file=work_dir / "canonical.inp",
                workdir=work_dir,
                module_dir=module_dir,
                toppar_dir=toppar_dir,
                variables=variables,
                seen_variables=set(),
            )
            if not isinstance(resolved, Path):
                resolved = _resolve_reference(
                    token=value,
                    current_file=work_dir / "canonical.inp",
                    workdir=work_dir,
                    module_dir=module_dir,
                    toppar_dir=toppar_dir,
                    variables=variables,
                )
            if not isinstance(resolved, Path):
                break

            canonical_name = canonical_names.get(resolved.resolve())
            if canonical_name is None:
                break
            if canonical_name.startswith(("module/", "toppar/")):
                # install-tree files keep their MODULE:/TOPPAR: spelling
                break

            if not value.startswith(("$", "&")):
                # a variable *reference* is already location-independent; rewriting it
                # would replace the CNS symbol name itself rather than a filename
                aliases[value] = canonical_name
            count_match = _COUNT_SUFFIX_REFERENCE_PATTERN.fullmatch(value.strip())
            if count_match is not None:
                # The dependency scanner has already resolved this expression
                # against the original count. Bind the computed variable to
                # that canonical pin directly so the canonical script remains
                # executable after the scheduling-only count is erased.
                aliases[value] = f'"{canonical_name}"'
                base_value = _resolve_variable_text(
                    count_match.group("base"),
                    variables,
                )
                if base_value:
                    aliases[base_value] = canonical_name
            break
    return aliases


def _resolve_variable_text(token: str, variables: dict[str, str]) -> Optional[str]:
    """Resolve a textual CNS variable reference without resolving filesystem paths."""
    seen: set[str] = set()
    while token.startswith(("$", "&")):
        variable_name = token[1:]
        if variable_name in seen or variable_name not in variables:
            return None
        seen.add(variable_name)
        token = variables[variable_name]
    return token


def _canonical_role_variable(variable: str, value: str) -> str:
    """Return the variable name that carries a dependency's stable role."""
    match = _COUNT_SUFFIX_REFERENCE_PATTERN.fullmatch(value.strip())
    if match is not None and match.group("base").startswith(("$", "&")):
        return match.group("base")[1:].lower()
    return variable.lower()


def _canonical_dependency_names(
    paths: Sequence[Path],
    module_dir: Path,
    toppar_dir: Path,
    variables: dict[Path, str],
) -> dict[Path, str]:
    """Assign stable roles in dependency first-reference order."""
    names: dict[Path, str] = {}
    counters = {"pdb": 0, "psf": 0, "generic": 0}
    named_roles = (
        ("unambig", "canonical-unambig.tbl"),
        ("hbond", "canonical-hbond.tbl"),
        ("ambig", "canonical-ambig.tbl"),
        ("dihe", "canonical-dihe.tbl"),
        ("sym", "canonical-symmetry.tbl"),
        ("tensor", "canonical-tensor.tbl"),
        ("ligand_top", "canonical-ligand.top"),
        ("ligand_param", "canonical-ligand.param"),
    )
    for path in paths:
        if path.is_relative_to(module_dir):
            names[path] = f"module/{path.relative_to(module_dir).as_posix()}"
            continue
        if path.is_relative_to(toppar_dir):
            names[path] = f"toppar/{path.relative_to(toppar_dir).as_posix()}"
            continue
        variable = variables.get(path, "")
        named = next(
            (
                name
                for marker, name in named_roles
                if re.search(rf"(?:^|_){re.escape(marker)}(?:_|$)", variable)
            ),
            None,
        )
        if named is not None and named not in names.values():
            names[path] = named
            continue
        logical_name = _strip_known_compression_suffix(path.name)
        suffix = Path(logical_name).suffix.lower()
        if suffix in (".pdb", ".psf"):
            counters[suffix[1:]] += 1
            names[path] = f"canonical-input-{counters[suffix[1:]]}{suffix}"
        elif suffix == ".tbl" and variable.startswith(("input_aa_", "input_cgtbl_")):
            counters["generic"] += 1
            names[path] = f"canonical-cg-input-{counters['generic']}.tbl"
        else:
            counters["generic"] += 1
            names[path] = f"canonical-input-{counters['generic']}{suffix}"
    return names


def _canonicalize_install_paths(
    script: str,
    module_dir: Path,
    toppar_dir: Path,
) -> str:
    """Give absolute install-tree paths their environment-relative CNS spelling.

    ``MODULE:`` and ``TOPPAR:`` are resolved by CNS through environment variables,
    so a reference spelled that way is already independent of where HADDOCK3 is
    installed. Paths written out in full are not, and reach the canonical form even
    when the recipe never reads them -- which is how the install path used to enter
    the identity of every topology job.
    """

    def replace(match: re.Match[str]) -> str:
        candidate = Path(match.group("path")).resolve()
        for root, prefix in ((module_dir, "MODULE:"), (toppar_dir, "TOPPAR:")):
            if candidate.is_relative_to(root):
                return f"{prefix}{candidate.relative_to(root).as_posix()}"
        return match.group(0)

    return re.sub(r'(?<![\w.-])(?P<path>/[^\s"\';]+)', replace, script)


def _rewrite_canonical_script(
    script: str,
    work_dir: Path,
    module_dir: Path,
    toppar_dir: Path,
    dependency_names: dict[Path, str],
    output_names: dict[Path, str],
    text_names: Optional[dict[str, str]] = None,
) -> str:
    """Replace only resolved job-specific path spellings in CNS text.

    Two rules keep the result both canonical and executable:

    - install-tree references keep their ``MODULE:``/``TOPPAR:`` spelling. The
      ``module/`` and ``toppar/`` names are pin names for the checksum tree; writing
      them into the script instead would leave the top-level input and the module
      scripts it includes disagreeing about what ``MODULE`` points at.
    - only *path* spellings are rewritten, never a bare basename, so that an input
      and an output sharing a basename cannot consume each other's binding.
    """
    result = _canonicalize_install_paths(script, module_dir, toppar_dir)
    job_paths = {
        path: name
        for path, name in dependency_names.items()
        if not name.startswith(("module/", "toppar/"))
    }
    for path, name in {**job_paths, **output_names}.items():
        candidates = {str(path), path.as_posix()}
        candidates.add(os.path.relpath(path, start=work_dir))
        for match in re.finditer(
            r'(?<![\w.-])(?P<path>(?:\.\.?/|/)[^\s"\';]+)',
            result,
        ):
            candidate = match.group("path")
            if _absolute_path(Path(candidate), work_dir) == path:
                candidates.add(candidate)
        for candidate in sorted(candidates, key=len, reverse=True):
            if candidate:
                result = _replace_script_token(result, candidate, name)
    for candidate, name in sorted(
        (text_names or {}).items(),
        key=lambda item: len(item[0]),
        reverse=True,
    ):
        if candidate:
            result = _replace_script_token(result, candidate, name)
    # ``count`` is the generated structure index: it names outputs and, via
    # ``"name" + "_" + encode($count)``, some reads.  Those reads are resolved
    # above, before this point, so what is left is a pure locator.  Erase it
    # for every shape -- a job's identity is its inputs and its seed, and with
    # seeds derived from content the schedule's numbering must not re-enter
    # identity through the back door.
    result = _canonicalize_locator_count_assignment(result)
    result = _canonicalize_default_molecule_flags(result)
    return _canonicalize_logging_level(result)


def _replace_script_token(script: str, token: str, replacement: str) -> str:
    """Replace a path-like token without matching inside another path token."""
    pattern = re.compile(rf"(?<![A-Za-z0-9_./-]){re.escape(token)}(?![A-Za-z0-9_./-])")
    return pattern.sub(replacement, script)


def _canonicalize_locator_count_assignment(script: str) -> str:
    """Erase generated structure indices with a valid, inert CNS value."""
    return _LOCATOR_COUNT_ASSIGNMENT_PATTERN.sub(
        r"\g<prefix>1\g<suffix>",
        script,
    )


def _canonicalize_default_molecule_flags(script: str) -> str:
    """Drop only surplus generated molecule flags which CNS cannot address.

    Refinement modules expand these entries to the number of incoming models,
    although the flags describe molecules, not models.  Extra ``false``
    assignments must not make an otherwise identical refinement job miss the
    cache. The first ``ncomponents`` entries are not inert: CNS indexes them
    dynamically, so removing those makes the canonical script invalid.
    """
    component_match = re.search(
        r"(?im)^\s*eval(?:uate)?\s*\(\s*\$ncomponents\s*=\s*(\d+)\s*\)",
        script,
    )
    if component_match is None:
        return script
    ncomponents = int(component_match.group(1))

    pattern = re.compile(
        r"(?im)^\s*eval\s*\(\s*\$mol_(?:fix_origin|shape)_"
        r"(?P<index>\d+)\s*=\s*false\s*\)\s*\n?"
    )
    return pattern.sub(
        lambda match: "" if int(match.group("index")) > ncomponents else match.group(0),
        script,
    )


def _canonicalize_logging_level(script: str) -> str:
    """Normalize CNS interpreter verbosity, which cannot affect job artifacts."""
    return re.sub(
        r'(?P<prefix>\$log_level\s*=\s*)"[^"]*"',
        r'\g<prefix>"canonical-log-level"',
        script,
    )


def _assert_output_bindings(
    script: str,
    canonical_output_names: Sequence[str],
) -> None:
    """The script must write exactly the outputs the mapping declares.

    Output shape is part of the transformation, so a script whose
    ``$output_pdb_filename`` says something other than the declared canonical name
    is describing a different computation from the one being checksummed.
    """
    for variable, canonical in (
        ("output_pdb_filename", "canonical-output.pdb"),
        ("output_psf_filename", "canonical-output.psf"),
    ):
        match = re.search(rf'\${variable}\s*=\s*"(?P<name>[^"]*)"', script)
        if match is None:
            continue
        if canonical not in canonical_output_names:
            raise ValueError(
                f"Canonical CNS script writes ${variable} but no {canonical!r} "
                "output was declared"
            )
        if match.group("name") != canonical:
            raise ValueError(
                f"Canonical CNS script binds ${variable} to "
                f"{match.group('name')!r} instead of the declared {canonical!r}"
            )


def _assert_canonical_script(
    script: str,
    work_dir: Path,
    module_dir: Path,
    toppar_dir: Path,
    paths: Sequence[Path],
    canonical_names: Sequence[str] = (),
    canonical_output_names: Sequence[str] = (),
) -> None:
    """Reject location-dependent canonical scripts before they become identity."""
    _assert_output_bindings(script, canonical_output_names)
    scanned = script
    for name in sorted(canonical_names, key=len, reverse=True):
        if name:
            scanned = scanned.replace(name, "\x00")
    leaked = [str(work_dir), str(module_dir), str(toppar_dir)]
    leaked.extend(path.name for path in paths if path.name)
    for token in leaked:
        if token and token in scanned:
            raise ValueError(
                f"Canonical CNS script leaked {token!r} from job in {work_dir}"
            )
    match = re.search(r"(?:^|/)\d+_[A-Za-z][A-Za-z0-9_]*", scanned)
    if match:
        raise ValueError(
            f"Canonical CNS script leaked step-folder token {match.group(0)!r}"
        )


def _absolute_path(path: Path, work_dir: Path) -> Path:
    return path.resolve() if path.is_absolute() else (work_dir / path).resolve()


def _resolve_env_path(raw_path: str, workdir: Path) -> Path:
    path = Path(raw_path)
    if path.is_absolute():
        return path.resolve()
    return (workdir / path).resolve()


def _resolve_reference(
    *,
    token: str,
    current_file: Path,
    workdir: Path,
    module_dir: Path,
    toppar_dir: Path,
    variables: dict[str, str],
    seen_variables: Optional[set[str]] = None,
) -> Optional[Union[Path, list[Path], _IgnoredReference]]:
    seen_variables = seen_variables or set()
    indexed_reference = _INDEXED_VARIABLE_REFERENCE_PATTERN.fullmatch(token)
    if indexed_reference is not None:
        prefix = indexed_reference.group("prefix")[1:]
        indexed_variables = sorted(
            variable
            for variable in variables
            if re.fullmatch(rf"{re.escape(prefix)}\d+", variable)
        )
        if not indexed_variables:
            return None
        resolved_paths: list[Path] = []
        for variable in indexed_variables:
            resolved = _resolve_reference(
                token=f"${variable}",
                current_file=current_file,
                workdir=workdir,
                module_dir=module_dir,
                toppar_dir=toppar_dir,
                variables=variables,
                seen_variables=set(seen_variables),
            )
            if not isinstance(resolved, Path):
                return None
            resolved_paths.append(resolved)
        return resolved_paths
    resolved_from_variable = False
    if token.startswith(("$", "&")):
        variable_name = token[1:]
        if variable_name in seen_variables:
            return None
        seen_variables.add(variable_name)
        dynamic_prefix = variables.get(f"__dynamic_prefix__{variable_name}")
        if variable_name not in variables:
            if dynamic_prefix is not None:
                prefix_path = _resolve_reference(
                    token=dynamic_prefix,
                    current_file=current_file,
                    workdir=workdir,
                    module_dir=module_dir,
                    toppar_dir=toppar_dir,
                    variables=variables,
                    seen_variables=seen_variables,
                )
                if isinstance(prefix_path, Path):
                    return sorted(prefix_path.parent.glob(f"{prefix_path.name}*"))
            return None
        token = variables[variable_name]
        if token == "":
            return IGNORED_REFERENCE
        resolved_from_variable = True
        dynamic_count_path = _resolve_count_suffix_reference(
            token=token,
            current_file=current_file,
            workdir=workdir,
            module_dir=module_dir,
            toppar_dir=toppar_dir,
            variables=variables,
            seen_variables=seen_variables,
        )
        if dynamic_count_path is not None:
            return dynamic_count_path
        if token.startswith(("$", "&")):
            return _resolve_reference(
                token=token,
                current_file=current_file,
                workdir=workdir,
                module_dir=module_dir,
                toppar_dir=toppar_dir,
                variables=variables,
                seen_variables=seen_variables,
            )
        if dynamic_prefix is not None and any(
            fragment in token for fragment in ("+", "encode(")
        ):
            prefix_path = _resolve_reference(
                token=dynamic_prefix,
                current_file=current_file,
                workdir=workdir,
                module_dir=module_dir,
                toppar_dir=toppar_dir,
                variables=variables,
                seen_variables=seen_variables,
            )
            if isinstance(prefix_path, Path):
                return sorted(prefix_path.parent.glob(f"{prefix_path.name}*"))

    if not token or any(fragment in token for fragment in ("+", "encode(", "$", "&")):
        return None

    if token.startswith("MODULE:"):
        return (module_dir / token.split(":", 1)[1].lstrip("/")).resolve()

    if token.startswith("TOPPAR:"):
        return (toppar_dir / token.split(":", 1)[1].lstrip("/")).resolve()

    if token.startswith("MODULE/"):
        return (module_dir / token.removeprefix("MODULE/").lstrip("/")).resolve()

    if token.startswith("TOPPAR/"):
        return (toppar_dir / token.removeprefix("TOPPAR/").lstrip("/")).resolve()

    candidate = Path(token)
    if candidate.is_absolute():
        return candidate.resolve()
    relative_base = workdir if resolved_from_variable else current_file.parent
    return (relative_base / candidate).resolve()


def _extract_nonempty_guard_variable(line: str) -> Optional[str]:
    match = re.search(r'\$([A-Za-z0-9_]+)\s*#\s*""', line)
    if match is not None:
        return match.group(1)

    match = re.search(r"&BLANK%([A-Za-z0-9_]+)\s*=\s*false", line, re.IGNORECASE)
    if match is not None:
        return match.group(1)

    return None


def _resolve_count_suffix_reference(
    *,
    token: str,
    current_file: Path,
    workdir: Path,
    module_dir: Path,
    toppar_dir: Path,
    variables: dict[str, str],
    seen_variables: set[str],
) -> Optional[Path]:
    match = _COUNT_SUFFIX_REFERENCE_PATTERN.fullmatch(token.strip())
    if match is None:
        return None

    base = _resolve_reference(
        token=match.group("base"),
        current_file=current_file,
        workdir=workdir,
        module_dir=module_dir,
        toppar_dir=toppar_dir,
        variables=variables,
        seen_variables=set(seen_variables),
    )
    count = _resolve_literal_or_variable(
        match.group("count"),
        variables=variables,
    )
    if not isinstance(base, Path) or count is None:
        return None

    counted = Path(f"{base}{match.group('separator')}{count}")
    if counted.exists():
        return counted.resolve()
    if base.exists():
        return base.resolve()
    return None


def _resolve_literal_or_variable(
    token: str,
    *,
    variables: dict[str, str],
) -> Optional[str]:
    if token.isdigit():
        return token
    if not token.startswith(("$", "&")):
        return None
    variable = variables.get(token[1:])
    return variable if variable and variable.isdigit() else None


def _is_guarded_optional_reference(
    token: str,
    guard_stack: list[tuple[str, bool]],
) -> bool:
    if not token.startswith(("$", "&")):
        return False
    variable_name = token[1:]
    return any(
        guard_var == variable_name and is_optional
        for guard_var, is_optional in guard_stack
    )


def _extract_dynamic_toppar_prefix(value: str) -> Optional[str]:
    match = _DYNAMIC_TOPPAR_PREFIX_PATTERN.search(value)
    if match is None:
        return None
    return match.group("prefix")


def _normalize_assignment_value(value: str) -> str:
    value = value.strip()
    if len(value) >= 2 and value[0] == '"' and value[-1] == '"':
        return value[1:-1]
    return value


def _strip_known_compression_suffix(name: str) -> str:
    if name.endswith(".gz"):
        return name[:-3]
    return name
