[params]
glowworms = 200
steps = 100
swarms = 400
scoring = "fastdfire"
top = 10
receptor_chains = "A"
receptor_active = ""
receptor_passive = ""
ligand_chains = "B"
ligand_active = ""
ligand_passive = ""
noxt = true
noh = true
restraints = false