"""
HADDOCK 3 supported residues.

https://bianca.science.uu.nl/haddock2.4/library
"""
import re
import itertools as it
from functools import partial
from pathlib import Path
from collections import namedtuple

from haddock import toppar_path
from haddock.libs.libutil import transform_to_list


def read_supported_residues_from_top_file(topfile, regex, Residue):
    """
    Read residue from CNS topology file.

    Generic implementation.

    Parameters
    ----------
    topfile : str or pathlib.Path
        The path pointing to the HADDOCK `.top` file.

    regex : raw string
        The regex string to find the desired groups.

    Residue : namedtuple
        A named tuple that accepts arguments matching the groups
        generated by `re.findall(regex, topfile)`.
        For the implementation in this module we expect this Residue
        namedtuple has a `resname` and `name` parameters, though it is
        not mandatory.

    Returns
    -------
    tuple
        A tuple of Residue named tuples.
    """
    text = Path(topfile).read_text()
    groups = re.findall(regex, text)
    # transform_to_list is needed because some regex may return groups
    # of just one members, hence the `for g in groups` returns a string
    # instead of a list.
    residues = tuple(Residue(*transform_to_list(g)) for g in groups)
    return residues


# what we will need to inspect if the residues are allowed or not are
# the residue names. So it is nice to have a function that retrieve them
# from the respective named tuples.
def get_resnames(group):
    """Make a tuple with the 'resnames'."""
    return tuple(i.resname for i in group)


# functions here are defined by order of `ls` in `cns/toppar/*.top`
read_carbohydrate = partial(
    read_supported_residues_from_top_file,
    regex=r'\nRESIdue +(\w{1,3}) +!([a-zA-Z0-9-]+) .*\n',
    Residue=namedtuple('Carbo', ['resname', 'name']),
    )


read_dna_rna_allatom_hj_opls = partial(
    read_supported_residues_from_top_file,
    regex=r'\nRESIdue (\w{1,3}) ! +(.*)\n',
    Residue=namedtuple('DNABase', ['resname', 'name']),
    )


read_dna_rna_martini = partial(
    read_supported_residues_from_top_file,
    regex=r'\nRESIdue (\w{1,3}) *.*\n',
    Residue=namedtuple('DNARNABase', ['resname']),
    )


# https://regex101.com/r/QSVfT3/1
read_fragment_probes_supported = partial(
    read_supported_residues_from_top_file,
    regex=r'\n! *(\w+) *.*\nRESIdue +(\w{1,3}).*\n',
    Residue=namedtuple('FramentProbe', ['name', 'resname']),
    )


read_glycans_uu = partial(
    read_supported_residues_from_top_file,
    regex=r'\nRESIdue +(\w{1,3}).*! *([A-Za-z0-9-,]+).*\n',
    Residue=namedtuple('GlycansUU', ['resname', 'name']),
    )

# https://regex101.com/r/00Ktzf/1
read_ions = partial(
    read_supported_residues_from_top_file,
    regex=r'\nRESIdue (\w{1,4}) {(\w+) [\+|\-]?\d.*}\n.*\n *ATOM (\w{1,2}[\+|\-]?\d) .* CHARge=([-\+]?\d).*\nEND {\w*}\n',
    Residue=namedtuple('Ion', ['resname', 'name', 'charge', 'atom']),
    )

# https://regex101.com/r/5Kc21W/1
read_multiatom_ions = partial(
    read_supported_residues_from_top_file,
    regex=r'\nRESIdue (\w{1,4}) {(\w+)}\n  GROUP\n(?:    ATOM.*\n)+\n(?:  BOND.*\n)+\nEND.*\n',
    Residue= namedtuple('MultiatomIon', ['resname', 'name']),
    )





# must be defined as HETATM
carbotop = Path(toppar_path, 'carbohydrate.top')
supported_carbohydrates = read_carbohydrate(carbotop)
supported_carboy_resnames = get_resnames(supported_carbohydrates)

# must be defined as HETATM
supported_ions = read_ions(Path(toppar_path, 'ion.top'))
supported_ion_names = tuple(i.name for i in supported_ions)
supported_ion_resnames = get_resnames(supported_ions)

# must be defined as HETATM
supported_multiatom_ions = read_multiatom_ions(Path(toppar_path, 'ion.top'))
supported_multiatom_ions_resnames = get_resnames(supported_multiatom_ions)

fragprob = Path(toppar_path, 'fragment_probes.top')
supported_fragment_probes = read_fragment_probes_supported(fragprob)
supported_fragment_probes_resname = get_resnames(supported_fragment_probes)

dna_rna_allatom = Path(toppar_path, 'dna-rna-allatom-hj-opls-1.3.top')
supported_dna_rna_allatom = read_dna_rna_allatom_hj_opls(dna_rna_allatom)
supported_dna_rna_allatom_resnames = get_resnames(supported_dna_rna_allatom)


dna_rna_martini = Path(toppar_path, 'dna-rna-CG-MARTINI-2-1p.top')
supported_dna_rna = read_dna_rna_martini(dna_rna_martini)
supported_dna_rna_resnames = get_resnames(supported_dna_rna)

glycansuu = Path(toppar_path, 'glycans-uu.top')
supported_glycans_uu = read_glycans_uu(glycansuu)
supported_glycans_uu_resnames = get_resnames(supported_glycans_uu)

# must be defined as HETATM
supported_cofactors = (
    'HEB',  # Heme-B
    'HEC',  # Heme-C
    )

# must be defined as ATOM
supported_nucleic_acid_bases = (
    # DNA
    'DA',  # Adenine
    'DC',  # Cytosine
    'DG',  # Guanidine
    'DT',  # Thymidine

    # RNA
    'A',  # Adenine
    'C',  # Cytosine
    'G',  # Guanidine
    'U',  # Uridine
    )

# must be defined as ATOM
supported_modified_amino_acids = (
    'ACE',  # N-terminal acetyl group
    'ALY',  # Acetylated LYS
    'ASH',  # protonated ASP
    'CFE',  # CYS with an iron sulfur cluster
    'CSP',  # phosphorylated CYS
    'CTN',  # C-terminal amide group
    'CYC',  # special for covalent docking - vdw of Sulphur reduced
    'CYF',  # CYS without the sulfur H (for coordinating metals)
    'CYM',  # CYS with MTSL grouped
    'DDZ',  # 3,3,-dihydrozy ALA
    'GLH',  # protonated GLU
    'HYP',  # 4R-hydroxyproline
    'M3L',  # trimethyl LYS
    'MLY',  # dimethyl LYS
    'MLZ',  # monomethyl LYS
    'MSE',  # Selenomethionine
    'NEP',  # NE phosphorylated HIS
    'NME',  # C-terminal N-Methyl
    'PNS',  # Phosphopanthenite Serine
    'PTR',  # O-Phosphotyrosine
    'SEP',  # phosphorylated SER
    'TOP',  # phosphorylated THR
    'TYP',  # phosphorylated TYR
    'PTR',  # phosphorylated TYR (also)
    'TYS',  # sulfonated TYR.
    )

supported_natural_amino_acids = (
    'ALA',
    'ARG',
    'ASN',
    'ASP',
    'CYS',
    'GLU',
    'GLN',
    'GLY',
    'HIS',
    'HIP',
    'HIE',
    'HID',
    'ILE',
    'LEU',
    'LYS',
    'MET',
    'PHE',
    'PRO',
    'SER',
    'THR',
    'TRP',
    'TYR',
    'VAL',
    )

supported_atom = set(it.chain(
    supported_natural_amino_acids,
    supported_modified_amino_acids,
    supported_nucleic_acid_bases,
    ))

supported_hetatm = set(it.chain(
    supported_cofactors,
    supported_multiatom_ions,
    supported_ions,
    supported_ion_resnames,
    supported_carbohydrates,
    ))



# must be defined as HETATM
#ion_charges = {
#    'AG': "+1",  # Silver
#    'AL': "+3",  # Aluminium
#    'AU': "+1",  # Gold
#    'BR': "-1",  # Bromine
#    'CA': "+2",  # Calcium
#    'CD': "+2",  # Cadmium
#    'CL': "-1",  # Chlore
#    'CO': "+2",  # Cobalt
#    'CR': "+3",  # Chromium
#    'CS': "+1",  # Cesium
#    'CU': "+1",  # Copper
#    'F': "-1",   # Fluor
#    'FE': "+2",  # Iron
#    'HG': "+2",  # Mercury
#    'HO': "+3",  # Holmium
#    'I': "-1",   # Iodine
#    'IR': "+3",  # Iridium
#    'K': "+1",   # Potassium
#    'KR': "+2",  # Krypton
#    'LI': "+1",  # Lithium
#    'MG': "+2",  # Magnesium
#    'MN': "+2",  # Manganese
#    'MO': "+2",  # Molybdenum
#    'NA': "+1",  # Sodium
#    'NI': "+2",  # Nickel
#    'OS': "+6",  # Osmium
#    'PB': "+2",  # Lead
#    'PT': "+2",  # Platinum
#    'SR': "+2",  # Strontium
#    'U': "+2",  # Uranium
#    'V': "+2",  # Vanadium
#    'YB': "+3",  # Ytterbium
#    'ZN': "+2",  # Zinc
#    }

## must be defined as HETATM
#supported_carbohydrates = (
#    'A2G',   # 2-N-acetyl-alpha-D-glucopyranose, different stereochemistry at C4
#    'BGC',  # beta-D-glucopyranose
#    'BMA',  # beta-D-mannopyronose
#    'FCA',  # alpha-D-fucopyranose
#    'FCB',  # beta-D-fucopyranose
#    'FUC',  # alpha-L-fucopyranose
#    'FUL',  # beta-L-fucopyranose
#    'GAL',  # (GLB): beta-D-galactopyranose
#    'GLA',  # alpha-D-galactopyranose
#    'GLC',  # alpha-D-glucopyranose
#    'MAN',  # alpha-D-mannopyranose
#    'NAG',  # 2-N-acetyl-beta-D-glucopyranose
#    'NDG',  # 2-N-acetyl-alpha-D-glucopyranose
#    'NGA',  # 2-N-acetyl-beta-D-galactopyranose
#    'SIA',  # alpha-N-acetyl neuraminic acid
#    'SIB',  # beta-N-acetyl neuraminic acid
#    'XYP',  # beta-D-xylopyranose
#    )


