# ====================================================================
# Rigid-body docking example

# in which order the steps must be executed?
order = ["topoaa",
         "rigidbody",
         "seletop",
         "flexref",
         "mdref",
         "clustfcc",]

# directory in which the scoring will be done
run_dir = "run1"

# ensemble to be scored
molecules =  [
    "../data/1a2k_l_u.pdb",
    "../data/1a2k_r_u.pdb"
    ]

# ====================================================================
# Parameters for each stage are defined below, prefer full paths
#####################################################################
# WARNING: THE PARAMETERS HERE ARE ILLUSTRATIVE
#  THE WORKFLOW IS WORK-IN-PROGRESS
#####################################################################
[topoaa]
autohis = true

[rigidbody]
ambig = '../data/1a2k_ti.tbl'
sampling = 20

[seletop]
select = 5

[flexref]
ambig = '../data/1a2k_ti.tbl'
cool1_steps = 500

[mdref]
ambig = '../data/1a2k_ti.tbl'
cool1_steps = 10

[clustfcc]
contact_distance_cutoff = 5.0
fraction_cutoff = 0.6
threshold = 4

# ====================================================================

