#!/bin/csh
#
setenv WDIR /data/capri/Capri47/Target160/analysis/ana_scripts
cat <<_Eod_ >statistics
#===============================================================
# Target160 combined analysis
#===============================================================
#
_Eod_

set statfile=structures.ranking

mkdir molscript
foreach i (target46-haddock_*.pdb)
  \cp $i `echo molscript/$i |sed -e 's/_1//'`
end

cd molscript
foreach i (*.pdb)
  delete_h.csh $i
  \rm $i.tmp
  profit <<_Eod_
    refe $WDIR/target46_refe.pdb
    zone A*
    atom CA
    mobi $i
    fit
    write $i
    quit
_Eod_
  cat <<_Eod1_>$i:r.molin
! MolScript v2.1 input file
! generated by MolAuto v1.1.1

plot

  window 80;
  background white;
_Eod1_
  echo 'read mol "'$i'";' >>$i:r.molin
  cat <<_Eod2_>>$i:r.molin

  transform atom *
    by centre position atom *
    by rotation x 180.0
    by rotation x -121.224
    by rotation y -39.8570
    by rotation z 65.5133;


_Eod2_

  set isel=`echo $i`
  set energies1=`grep $isel" " ../$statfile |awk '{print "Haddock="$3" BSA="$4" Edesol="$5" Dfire="$8}'`
  set energies2=`grep $isel" " ../$statfile |awk '{print "fc-elec="$6" fc-desol="$7" probe="$9" combined="$11}'`
  echo  'label -30.0 -37.0 0.0 "'$i'";'>>$i:r.molin
  echo  'label -5.0  -41.0 0.0 "'$energies1'";'>>$i:r.molin
  echo  'label -4.0  -45 0.0 "'$energies2'";'>>$i:r.molin

  cat <<_Eod3_>>$i:r.molin

 set colourparts on, residuecolour amino-acids rainbow;

  coil from A1 to A13;
  helix from A13 to A20;
  coil from A20 to A24;
  strand from A24 to A31;
  coil from A31 to A36;
  helix from A36 to A41;
  coil from A41 to A45;
  strand from A45 to A52;
  coil from A52 to A54;
  helix from A54 to A58;
  coil from A58 to A61;
  strand from A61 to A68;
  coil from A68 to A82;
  strand from A82 to A85;
  coil from A85 to A91;
  helix from A91 to A94;
  coil from A94 to A104;
  helix from A104 to A111;
  coil from A111 to A117;
  strand from A117 to A124;
  coil from A124 to A130;
  helix from A130 to A133;
  coil from A133 to A135;
  helix from A135 to A139;
  coil from A139 to A146;
  strand from A146 to A149;
  coil from A149 to A154;
  strand from A154 to A161;
  coil from A161 to A164;
  coil from B1 to B3;
  helix from B3 to B9;
  coil from B9 to B11;
  helix from B11 to B14;
  coil from B14 to B24;
  strand from B24 to B29;
  turn from B29 to B30;
  helix from B30 to B33;
  coil from B33 to B37;
  helix from B37 to B45;
  coil from B45 to B52;
  helix from B52 to B61;
  coil from B61 to B88;
  helix from B88 to B91;
  coil from B91 to B93;
  strand from B93 to B102;
  coil from B102 to B107;
  strand from B107 to B118;

  set colourparts on;
  ball-and-stick in residue A165;
  cpk in residue B119;

end_plot

_Eod3_
  molscript <$i:r.molin>$i:r.ps
end
cd ..

#goto exit

foreach i (target46-haddock_*.pdb)
  mkdir $i:r
  cd $i:r
  dimplot ../$i A B
  cd ..
end

foreach i (target46-haddock*_1.pdb)
  if (-e $i:r/ligplot.sum) then
    set rootfile=`echo $i |sed s/_1\.pdb//` 
    cat $rootfile'_'[1-5]/ligplot.sum |sort -n -k3 -k7> $rootfile.ligplot 
  endif
  rm -rf $rootfile'_'[1-5]
end

exit:
