"""Build and perturb HADDOCK3 configuration files structurally.

Base workflows are described as data and rendered to ``.cfg`` text, rather
than parsed out of the ``examples/`` tree and edited as strings.  Every Phase 2
perturbation is then a well-defined operation on that structure -- insert a
step, change one parameter, swap two molecules -- instead of a regular
expression that may silently match nothing.
"""

from __future__ import annotations

import copy
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any


@dataclass
class Step:
    """One ``[module]`` block, with its optional ``[module.sub]`` subsections."""

    module: str
    params: dict[str, Any] = field(default_factory=dict)
    subsections: dict[str, dict[str, Any]] = field(default_factory=dict)


@dataclass
class Config:
    """A whole HADDOCK3 configuration: top-level parameters plus steps."""

    top: dict[str, Any] = field(default_factory=dict)
    steps: list[Step] = field(default_factory=list)

    def copy(self) -> "Config":
        return copy.deepcopy(self)

    def find(self, module: str, occurrence: int = 0) -> Step:
        """Return the ``occurrence``-th step of ``module`` (0-based)."""
        matches = [step for step in self.steps if step.module == module]
        if occurrence >= len(matches):
            raise KeyError(f"no step {module}#{occurrence} in this config")
        return matches[occurrence]

    def index_of(self, module: str, occurrence: int = 0) -> int:
        seen = 0
        for position, step in enumerate(self.steps):
            if step.module == module:
                if seen == occurrence:
                    return position
                seen += 1
        raise KeyError(f"no step {module}#{occurrence} in this config")

    def render(self) -> str:
        lines = ["# Generated by the CNS caching contract-compliance suite.", ""]
        for key, value in self.top.items():
            lines.append(f"{key} = {_render_value(value)}")
        lines.append("")
        for step in self.steps:
            lines.append(f"[{step.module}]")
            for key, value in step.params.items():
                lines.append(f"{key} = {_render_value(value)}")
            for name, params in step.subsections.items():
                lines.append(f"[{step.module}.{name}]")
                for key, value in params.items():
                    lines.append(f"{key} = {_render_value(value)}")
            lines.append("")
        return "\n".join(lines) + "\n"

    def write(self, path: Path) -> Path:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(self.render(), encoding="utf-8")
        return path


def _render_value(value: Any) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return repr(value)
    if isinstance(value, Path):
        return f'"{value.as_posix()}"'
    if isinstance(value, str):
        return f'"{value}"'
    if isinstance(value, (list, tuple)):
        return "[" + ", ".join(_render_value(item) for item in value) + "]"
    raise TypeError(f"cannot render {value!r} in a HADDOCK3 config")


#: Modules whose jobs run through CNS and are therefore cacheable.  The suite
#: treats every other module as an uncacheable neighbour.
CACHEABLE_MODULES = frozenset(
    {
        "topoaa",
        "topocg",
        "rigidbody",
        "flexref",
        "emref",
        "mdref",
        "emscoring",
        "mdscoring",
        "cgtoaa",
    }
)

#: Cacheable modules that emit a topology ``.psf`` alongside the ``.pdb``.
TOPOLOGY_MODULES = frozenset({"topoaa", "topocg"})
