"""Things related to residues."""

THREE_TO_ONE = {
    "CYS": "C",
    "ASP": "D",
    "SER": "S",
    "GLN": "Q",
    "LYS": "K",
    "ILE": "I",
    "PRO": "P",
    "THR": "T",
    "PHE": "F",
    "ASN": "N",
    "GLY": "G",
    "HIS": "H",
    "LEU": "L",
    "ARG": "R",
    "TRP": "W",
    "ALA": "A",
    "VAL": "V",
    "GLU": "E",
    "TYR": "Y",
    "MET": "M",
    }

ONE_TO_THREE = {
    "C": "CYS",
    "D": "ASP",
    "S": "SER",
    "Q": "GLN",
    "K": "LYS",
    "I": "ILE",
    "P": "PRO",
    "T": "THR",
    "F": "PHE",
    "N": "ASN",
    "G": "GLY",
    "H": "HIS",
    "L": "LEU",
    "R": "ARG",
    "W": "TRP",
    "A": "ALA",
    "V": "VAL",
    "E": "GLU",
    "Y": "TYR",
    "M": "MET",
    }

CODE_TO_AA = {
    1: "ALA",
    2: "ARG",
    3: "ASP",
    4: "ASN",
    5: "CYS",
    6: "GLU",
    7: "GLN",
    8: "GLY",
    9: "HIS",
    10: "ILE",
    11: "LEU",
    12: "LYS",
    13: "MET",
    14: "PHE",
    15: "PRO",
    16: "SER",
    17: "THR",
    18: "TRP",
    19: "TYR",
    20: "VAL",
    }

AA_TO_CODE = {
    "ALA": 1,
    "ARG": 2,
    "ASP": 3,
    "ASN": 4,
    "CYS": 5,
    "GLU": 6,
    "GLN": 7,
    "GLY": 8,
    "HIS": 9,
    "ILE": 10,
    "LEU": 11,
    "LYS": 12,
    "MET": 13,
    "PHE": 14,
    "PRO": 15,
    "SER": 16,
    "THR": 17,
    "TRP": 18,
    "TYR": 19,
    "VAL": 20,
    }
