#!/bin/csh
#
setenv WDIR /data/capri/Capri47/Target160/analysis/ana_scripts
cat <<_Eod_ >statistics
#===============================================================
# Target160 
#===============================================================
#
_Eod_

if (-e clusters_best4ranked.scores) then
  cat clusters_best4ranked.scores >>statistics
  set statfile=clusters_best4ranked.scores
else if (-e clusters_best4.scores) then
  cat clusters_best4.scores >>statistics
  set statfile=clusters_best4.scores
else if (-e  clusters_best2ranked.scores) then
  cat clusters_best2ranked.scores >>statistics  
  set statfile=clusters_best2ranked.scores
else if (-e  clusters_best2.scores) then
  cat clusters_best2.scores >>statistics  
  set statfile=clusters_best2.scores
else if (-e  clusters_best1ranked.scores) then
  cat clusters_best1ranked.scores >>statistics  
  set statfile=clusters_best1ranked.scores
else if (-e  clusters_best1.scores) then
  cat clusters_best1.scores >>statistics  
  set statfile=clusters_best1.scores
endif

mkdir molscript
foreach i (target29*_1.pdb)
  \cp $i `echo molscript/$i |sed -e 's/_1//'`
end

cd molscript
foreach i (*.pdb)
  delete_h.csh $i
  \rm $i.tmp
  profit <<_Eod_
    refe $WDIR/target29_refe.pdb
    zone A835-A945
    zone B835-B945
    atom CA
    mobi $i
    fit
    write $i
    quit
_Eod_
  cat <<_Eod1_>$i:r.molin
! MolScript v2.1 input file
! generated by MolAuto v1.1.1

plot

  window 130;
  background white;
_Eod1_
  echo 'read mol "'$i'";' >>$i:r.molin
  cat <<_Eod2_>>$i:r.molin

  transform atom * by centre position atom *;

_Eod2_

  set isel=`echo $i |sed -e 's/target29_run2_//' -e 's/\.pdb//'`
  set energies1=`grep $isel" " ../$statfile |awk '{print "Haddock="$5"+-"$6" BSA="$7"+-"$8" Edesol="$9"+-"$10" Dfire="$15"+-"$16}'`
  set energies2=`grep $isel" " ../$statfile |awk '{print "fc-elec="$11"+-"$12" fc-desol="$13"+-"$14" probe="$17"+-"$18" combined="$21"+-"$22}'`
  echo  'label -35.0 -62.0 0.0 "'$i'";'>>$i:r.molin
  echo  'label -5.0  -68.0 0.0 "'$energies1'";'>>$i:r.molin
  echo  'label -4.0  -74.0 0.0 "'$energies2'";'>>$i:r.molin

  cat <<_Eod3_>>$i:r.molin


  set planecolour rgb 0.0 0.0 1.0;
  set plane2colour rgb 0.0 0.5 1.0;

  coil from A575 to A579;
  helix from A579 to A591;
  coil from A591 to A598;
  strand from A598 to A603;
  turn from A603 to A604;
  helix from A604 to A619;
  coil from A619 to A622;
  helix from A622 to A625;
  coil from A625 to A628;
  strand from A628 to A633;
  coil from A633 to A640;
  helix from A640 to A657;
  coil from A657 to A659;
  helix from A659 to A662;
  turn from A662 to A663;
  strand from A663 to A666;
  turn from A666 to A667;
  helix from A667 to A673;
  turn from A673 to A674;
  strand from A674 to A677;
  coil from A677 to A680;
  helix from A680 to A683;
  coil from A683 to A687;
  helix from A687 to A704;
  coil from A704 to A713;
  helix from A713 to A717;
  coil from A717 to A719;
  helix from A719 to A722;
  coil from A722 to A727;
  helix from A727 to A730;
  coil from A730 to A734;
  helix from A734 to A745;
  coil from A745 to A756;
  strand from A756 to A762;
  coil from A762 to A765;
  strand from A765 to A771;
  coil from A771 to A784;
  helix from A784 to A796;
  coil from A796 to A804;
  helix from A804 to A814;
  coil from A814 to A819;
  helix from A819 to A833;

  set planecolour rgb 1.0 0.5 0.0;
  set plane2colour rgb 1.0 1.0 0.0;

  coil from A833 to A842;
  helix from A842 to A848;
  turn from A848 to A849;
  strand from A849 to A852;
  coil from A852 to A858;
  helix from A858 to A883;
  coil from A883 to A906;
  strand from A906 to A912;
  coil from A912 to A918;
  strand from A918 to A922;
  coil from A922 to A925;
  strand from A925 to A930;
  coil from A930 to A934;
  helix from A934 to A947;

  set planecolour rgb 0.5 0.0 1.0;
  set plane2colour rgb 1.0 0.0 1.0;

  coil from B575 to B579;
  helix from B579 to B591;
  coil from B591 to B598;
  strand from B598 to B604;
  coil from B604 to B608;
  helix from B608 to B619;
  coil from B619 to B622;
  helix from B622 to B625;
  coil from B625 to B628;
  strand from B628 to B634;
  coil from B634 to B640;
  helix from B640 to B657;
  coil from B657 to B659;
  helix from B659 to B662;
  turn from B662 to B663;
  strand from B663 to B666;
  turn from B666 to B667;
  helix from B667 to B673;
  turn from B673 to B674;
  strand from B674 to B677;
  coil from B677 to B680;
  helix from B680 to B683;
  coil from B683 to B687;
  helix from B687 to B704;
  coil from B704 to B713;
  helix from B713 to B717;
  coil from B717 to B719;
  helix from B719 to B722;
  coil from B722 to B726;
  helix from B726 to B730;
  coil from B730 to B734;
  helix from B734 to B745;
  coil from B745 to B756;
  strand from B756 to B762;
  coil from B762 to B765;
  strand from B765 to B771;
  coil from B771 to B784;
  helix from B784 to B796;
  coil from B796 to B804;
  helix from B804 to B814;
  coil from B814 to B819;
  helix from B819 to B833;

  set planecolour rgb 1.0 0.0 0.0;
  set plane2colour rgb 1.0 0.5 0.0;

  coil from B833 to B842;
  helix from B842 to B848;
  turn from B848 to B849;
  strand from B849 to B852;
  coil from B852 to B858;
  helix from B858 to B883;
  coil from B883 to B890;
  helix from B890 to B893;
  coil from B893 to B897;
  strand from B897 to B899;
  coil from B899 to B903;
  strand from B903 to B912;
  coil from B912 to B918;
  strand from B918 to B922;
  coil from B922 to B925;
  strand from B925 to B930;
  coil from B930 to B934;
  helix from B934 to B947;

!  set transparency 0.2;
!  ball-and-stick in type WAT;

end_plot
_Eod3_
  molscript <$i:r.molin>$i:r.ps
end
cd ..

foreach i (target29_run2_*.pdb)
  mkdir $i:r
  cd $i:r
  dimplot ../$i A C
  \mv ligplot.sum ligplot.sumAC
  dimplot ../$i B C
  \mv ligplot.sum ligplot.sumBC
  dimplot ../$i A B
  cd ..
end

foreach i (target29_run2_*_1.pdb)
  if (-e $i:r/ligplot.sum) then
    set rootfile=`echo $i |sed s/_1\.pdb//` 
    cat $rootfile'_'[1-5]/ligplot.sum |sort -n +2 +6> $rootfile.ligplot 
    cat $rootfile'_'[1-5]/ligplot.sumAC $rootfile'_'[1-5]/ligplot.sumBC |sort -n +2 +6> $rootfile.ligplot-water 
  endif
end

foreach i ( *.ligplot *.ligplot-water )
  echo '===========================' >dum
  echo $i >>dum
  echo '===========================' >>dum
  cat $i >>dum
  \mv dum $i
end

exit:
