#!/bin/csh
#
setenv WDIR /data/capri/Capri47/Target160-scoring/ana_scripts
cat <<_Eod_ >statistics
#===============================================================
# Target160 combined analysis
#===============================================================
#
_Eod_

if (-e clusters_best5.scores) then
  cat clusters_best5.scores >>statistics
  set statfile=clusters_best5.scores
else if (-e clusters_best4.scores) then
  cat clusters_best4.scores >>statistics
  set statfile=clusters_best4.scores
else if (-e  clusters_best2.scores) then
  cat clusters_best2.scores >>statistics  
  set statfile=clusters_best2.scores
else if (-e  clusters_best1.scores) then
  cat clusters_best1.scores >>statistics  
  set statfile=clusters_best1.scores
endif

mkdir molscript
foreach i (target160*_1.pdb)
  \cp $i `echo molscript/$i |sed -e 's/_1//'`
end

cd molscript
foreach i (*.pdb)
  delete_h.csh $i
  \rm $i.tmp
  profit <<_Eod_
    refe $WDIR/target160_refe.pdb
    zone A*
    atom CA
    mobi $i
    fit
    write $i
    quit
_Eod_
  cat <<_Eod1_>$i:r.molin
! MolScript v2.1 input file
! generated by MolAuto v1.1.1

plot

  window 100;
  background white;
_Eod1_
  echo 'read mol "'$i'";' >>$i:r.molin
  cat <<_Eod2_>>$i:r.molin

  transform atom *
    by centre position atom *;


_Eod2_

  set isel=`echo $i |sed -e 's/target160_//' -e 's/\.pdb//'`
  set energies1=`grep $isel" " ../$statfile |awk '{print "Haddock="$5"+-"$6" BSA="$7"+-"$8" Edesol="$9"+-"$10" Dfire="$15"+-"$16}'`
  set energies2=`grep $isel" " ../$statfile |awk '{print "fc-elec="$11"+-"$12" fc-desol="$13"+-"$14" probe="$17"+-"$18" combined="$21"+-"$22}'`
  echo  'label -30.0 -39.0 0.0 "'$i'";'>>$i:r.molin
  echo  'label -5.0  -43.0 0.0 "'$energies1'";'>>$i:r.molin
  echo  'label -4.0  -47 0.0 "'$energies2'";'>>$i:r.molin

  cat <<_Eod3_>>$i:r.molin

  set colourparts on, residuecolour amino-acids rainbow;

  turn from A21 to A31;
  strand from A31 to A34;
  turn from A34 to A38;
  strand from A38 to A41;
  turn from A41 to A62;
  strand from A62 to A64;
  turn from A64 to A68;
  helix from A68 to A91;
  turn from A91 to A102;
  strand from A102 to A110;
  turn from A110 to A111;
  helix from A111 to A114;
  turn from A114 to A121;
  strand from A121 to A127;
  turn from A127 to A130;
  strand from A130 to A132;
  turn from A132 to A154;
  strand from A154 to A158;
  turn from A158 to A166;
  strand from A166 to A170;
  turn from A170 to A177;
  helix from A177 to A193;
  turn from A193 to A201;
  strand from A201 to A209;
  turn from A209 to A212;
  strand from A212 to A219;
  turn from A219 to A238;
  helix from A238 to A241;
  turn from A241 to A243;
  helix from A243 to A248;
  turn from A248 to B31;
  strand from B31 to B34;
  turn from B34 to B38;
  strand from B38 to B41;
  turn from B41 to B61;
  strand from B61 to B64;
  turn from B64 to B72;
  helix from B72 to B76;
  turn from B76 to B79;
  helix from B79 to B91;
  turn from B91 to B102;
  strand from B102 to B110;
  turn from B110 to B111;
  helix from B111 to B114;
  turn from B114 to B121;
  strand from B121 to B127;
  turn from B127 to B130;
  strand from B130 to B132;
  turn from B132 to B154;
  strand from B154 to B158;
  turn from B158 to B166;
  strand from B166 to B170;
  turn from B170 to B177;
  helix from B177 to B193;
  turn from B193 to B201;
  strand from B201 to B209;
  turn from B209 to B212;
  strand from B212 to B219;
  turn from B219 to B238;
  helix from B238 to B248;
  turn from B248 to C31;
  strand from C31 to C34;
  turn from C34 to C37;
  strand from C37 to C41;
  turn from C41 to C61;
  strand from C61 to C64;
  turn from C64 to C68;
  helix from C68 to C91;
  turn from C91 to C102;
  strand from C102 to C110;
  turn from C110 to C111;
  helix from C111 to C114;
  turn from C114 to C121;
  strand from C121 to C127;
  turn from C127 to C130;
  strand from C130 to C132;
  turn from C132 to C154;
  strand from C154 to C158;
  turn from C158 to C166;
  strand from C166 to C170;
  turn from C170 to C177;
  helix from C177 to C193;
  turn from C193 to C201;
  strand from C201 to C209;
  turn from C209 to C212;
  strand from C212 to C219;
  turn from C219 to C238;
  helix from C238 to C241;
  turn from C241 to C243;
  helix from C243 to C248;
  turn from C248 to D31;
  strand from D31 to D34;
  turn from D34 to D37;
  strand from D37 to D41;
  turn from D41 to D61;
  strand from D61 to D64;
  turn from D64 to D68;
  helix from D68 to D91;
  turn from D91 to D102;
  strand from D102 to D110;
  turn from D110 to D111;
  helix from D111 to D114;
  turn from D114 to D121;
  strand from D121 to D127;
  turn from D127 to D130;
  strand from D130 to D132;
  turn from D132 to D154;
  strand from D154 to D158;
  turn from D158 to D166;
  strand from D166 to D170;
  turn from D170 to D177;
  helix from D177 to D193;
  turn from D193 to D201;
  strand from D201 to D209;
  turn from D209 to D212;
  strand from D212 to D219;
  turn from D219 to D238;
  helix from D238 to D248;

end_plot

_Eod3_
  molscript <$i:r.molin>$i:r.ps
end
cd ..

#goto exit

foreach i (target160_*.pdb)
  mkdir $i:r_AB
  cd $i:r_AB
  dimplot ../$i A B
  cd ..
  mkdir $i:r_BC
  cd $i:r_BC
  dimplot ../$i B C
  cd ..
  mkdir $i:r_CD
  cd $i:r_CD
  dimplot ../$i C D
  cd ..
  mkdir $i:r_DA
  cd $i:r_DA
  dimplot ../$i D A
  cd ..
  mkdir $i:r_AC
  cd $i:r_AC
  dimplot ../$i A C
  cd ..
  mkdir $i:r_BD
  cd $i:r_BD
  dimplot ../$i B D
  cd ..
end

foreach i (target160_*_1.pdb)
  set rootfile=`echo $i |sed s/_1\.pdb//` 
  if (-e $i:r_AB/ligplot.sum) then
    cat $rootfile'_'[1-5]_[ABCD][ABCD]/ligplot.sum |sort -n -k3 -k7> $rootfile.ligplot 
  endif
  rm -rf $rootfile'_'[1-5]_[ABCD][ABCD]
end

foreach i ( *.ligplot *.ligplot-water )
  echo '===========================' >dum
  echo $i >>dum
  echo '===========================' >>dum
  cat $i >>dum
  \mv dum $i
end

exit:
