---
name: ci

on:
  push:
    branches: [main]
    paths:
      - src/*
      - tests/*
      - integration_tests/*
      - docs/*
      - pyproject.toml
      - setup.py
  pull_request:
  workflow_dispatch: ~
  schedule:
    - cron: "0 */6 * * *" # every 6 hours

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
      actions: read
      checks: write
    strategy:
      matrix:
        os: [macos-latest]
        python-version: ["3.12"]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: install haddock3 with extra dependencies
        run: pip install -e '.[dev]'

      - name: run unit tests
        run: >-
          pytest -v tests/test_libligand.py

      - name: run integration tests
        run: >-
          pytest -v integration_tests/test_topoaa.py::test_topoaa_module_ligand_automated
