---
name: pages

on:
  push:
    branches:
      - main

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  pages:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.10"

      - name: install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y openmpi-bin libopenmpi3 libopenmpi-dev

      - name: install haddock3 with extra dependencies
        run: pip install '.[dev,docs]'

      - name: Generate docs
        run: |
          cd docs
          make html

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: haddock3-docs

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
